/-
Copyright (c) 2026 Zhihao Gu, Qilong Wu, and Junchi Yang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zhihao Gu, Qilong Wu, Junchi Yang
-/
import BilevelLowerBoundLean.Basic
import BilevelLowerBoundLean.Transcript
import BilevelLowerBoundLean.ZeroChain
import BilevelLowerBoundLean.ZeroChainAnalytic
import BilevelLowerBoundLean.ZeroChainSmooth
import BilevelLowerBoundLean.ZeroChainDerivatives
import BilevelLowerBoundLean.ZeroChainBounds
import BilevelLowerBoundLean.ZeroChainGradient
import BilevelLowerBoundLean.ZeroChainHigher
import BilevelLowerBoundLean.FrontierExtractor
import BilevelLowerBoundLean.FrontierExtractorDerivatives
import BilevelLowerBoundLean.FrontierExtractorJets
import BilevelLowerBoundLean.FrontierExtractorQuantitative
import BilevelLowerBoundLean.FrontierGateQuantitative
import BilevelLowerBoundLean.HardInstance
import BilevelLowerBoundLean.HardInstanceAnalytic
import BilevelLowerBoundLean.CompositionScales
import BilevelLowerBoundLean.SoftProjectionQuantitative
import BilevelLowerBoundLean.PopulationRegularity
import BilevelLowerBoundLean.FullPopulationRegularity
import BilevelLowerBoundLean.HardObjectiveRegularity
import BilevelLowerBoundLean.ConditionWitness
import BilevelLowerBoundLean.Oracle
import BilevelLowerBoundLean.FreshSample
import BilevelLowerBoundLean.VisibleChainCylinder
import BilevelLowerBoundLean.Interface
import BilevelLowerBoundLean.HardOracleInterface
import BilevelLowerBoundLean.CoupledProcess
import BilevelLowerBoundLean.HaarGeometry
import BilevelLowerBoundLean.HaarProbability
import BilevelLowerBoundLean.ProgressBound
import BilevelLowerBoundLean.GapGradient
import BilevelLowerBoundLean.ParameterSelection
import BilevelLowerBoundLean.MainTheorem
import BilevelLowerBoundLean.WorstCaseQuantifiers
import BilevelLowerBoundLean.PaperFinalTheorem
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for completed modules

Opening this file in VS Code, or compiling it with Lake, prints the axioms on
which each completed theorem depends.  In particular, `sorryAx` must never
appear for a theorem marked complete in `FORMALIZATION_STATUS.md`.
-/

#print axioms BilevelLowerBound.progress_le_iff
#print axioms BilevelLowerBound.abs_le_threshold_of_progress_le
#print axioms BilevelLowerBound.progress_le_of_tail_bound
#print axioms BilevelLowerBound.progress_anti_threshold
#print axioms BilevelLowerBound.progress_quarter_rescaling
#print axioms BilevelLowerBound.extendQuery_ignores_gifted_information
#print axioms BilevelLowerBound.extendOutput_ignores_gifted_information
#print axioms BilevelLowerBound.chainQ_eq_zero_of_abs_left_le_half
#print axioms BilevelLowerBound.chainQ_neg_neg
#print axioms BilevelLowerBound.scaledChain_eq_link_sum
#print axioms BilevelLowerBound.chainQ_normalized_eq_zero
#print axioms BilevelLowerBound.gaussianKernel_integrable
#print axioms BilevelLowerBound.phiZero_hasDerivAt
#print axioms BilevelLowerBound.phiZero_contDiff
#print axioms BilevelLowerBound.psi_le_exp_one
#print axioms BilevelLowerBound.phiZero_deriv_le_sqrt_exp
#print axioms BilevelLowerBound.abs_chainQ_le
#print axioms BilevelLowerBound.scaledChain_gap_pointwise
#print axioms BilevelLowerBound.scaledChain_initial_gap
#print axioms BilevelLowerBound.expNegInvSqGlue_contDiff
#print axioms BilevelLowerBound.expNegInvSqGlue_iteratedDeriv_zero
#print axioms BilevelLowerBound.psi_contDiff
#print axioms BilevelLowerBound.psi_iteratedDeriv_eq_zero_of_le_half
#print axioms BilevelLowerBound.chainQ_contDiff
#print axioms BilevelLowerBound.iteratedFDeriv_chainQ_eq_zero_of_abs_fst_le_half
#print axioms BilevelLowerBound.unscaledChain_contDiff
#print axioms BilevelLowerBound.scaledChain_contDiff
#print axioms BilevelLowerBound.iteratedFDeriv_scaledChain
#print axioms BilevelLowerBound.iteratedFDeriv_scaledChain_three
#print axioms BilevelLowerBound.abs_psi_deriv_le
#print axioms BilevelLowerBound.chainQ_deriv_snd_le_neg_one
#print axioms BilevelLowerBound.abs_unscaledChain_gradient_coordinate_lt_twentyThree
#print axioms BilevelLowerBound.norm_unscaledChain_gradient_le
#print axioms BilevelLowerBound.abs_scaledChain_gradient_coordinate_le
#print axioms BilevelLowerBound.norm_scaledChain_gradient_le
#print axioms BilevelLowerBound.scaledChain_frontier_gradient_le
#print axioms BilevelLowerBound.exists_bound_psi_iteratedFDeriv
#print axioms BilevelLowerBound.norm_iteratedFDeriv_phiZero_le_five
#print axioms BilevelLowerBound.exists_common_bound_chainQ_three
#print axioms BilevelLowerBound.sum_linkDirection_norm_mul_le
#print axioms BilevelLowerBound.sum_linkDirection_norm_triple_le
#print axioms BilevelLowerBound.exists_unscaledChain_second_bound
#print axioms BilevelLowerBound.exists_unscaledChain_third_bound
#print axioms BilevelLowerBound.exists_scaledChain_second_bound
#print axioms BilevelLowerBound.exists_scaledChain_third_bound
#print axioms BilevelLowerBound.coordinateGate_eq_transition_abs
#print axioms BilevelLowerBound.frontierSummand_nonzero_index
#print axioms BilevelLowerBound.frontierExtractor_eq_zero_of_full_progress
#print axioms BilevelLowerBound.abs_frontierExtractor_le
#print axioms BilevelLowerBound.frontierExtractor_progress_cylinder
#print axioms BilevelLowerBound.frontierLinkGate_contDiff
#print axioms BilevelLowerBound.frontierExtractor_contDiff
#print axioms BilevelLowerBound.iteratedFDeriv_frontierExtractor_strict_cylinder
#print axioms BilevelLowerBound.iteratedFDeriv_frontierExtractor_progress_cylinder
#print axioms BilevelLowerBound.iteratedFDeriv_frontierSummand_zero_unless_frontier
#print axioms BilevelLowerBound.iteratedFDeriv_frontierExtractor_eq_frontier_summand
#print axioms BilevelLowerBound.iteratedFDeriv_frontierExtractor_eq_zero_of_full_progress
#print axioms BilevelLowerBound.exists_common_bound_frontierTransition_three
#print axioms BilevelLowerBound.exists_common_bound_coordinateGate_three
#print axioms BilevelLowerBound.frontierRadialProfile_contDiff
#print axioms BilevelLowerBound.frontierLinkGate_eq_radialProfile_norm_sq
#print axioms BilevelLowerBound.tailActivationNormSq_contDiff
#print axioms BilevelLowerBound.frontierLinkGate_eq_radialProfile_comp_tailActivationNormSq
#print axioms BilevelLowerBound.iteratedFDeriv_frontierRadialProfile_eq_zero_of_nine_sixteenths_lt
#print axioms BilevelLowerBound.exists_common_bound_frontierRadialProfile_three
#print axioms BilevelLowerBound.norm_iteratedFDeriv_chainLink_le
#print axioms BilevelLowerBound.norm_iteratedFDeriv_mul_scaled_le_eight
#print axioms BilevelLowerBound.norm_iteratedFDeriv_frontierExtractor_le_of_gate_bound
#print axioms BilevelLowerBound.iteratedFDeriv_tailActivation_apply
#print axioms BilevelLowerBound.sum_coordinate_product_sq_le
#print axioms BilevelLowerBound.norm_iteratedFDeriv_tailActivation_le
#print axioms BilevelLowerBound.norm_iteratedFDeriv_tailActivationNormSq_le_of_norm
#print axioms BilevelLowerBound.norm_iteratedFDeriv_frontierLinkGate_le
#print axioms BilevelLowerBound.exists_common_bound_frontierLinkGate_three
#print axioms BilevelLowerBound.exists_common_bound_frontierExtractor_three
#print axioms BilevelLowerBound.cutoffWeight_deriv_eq_zero_of_abs_le_one
#print axioms BilevelLowerBound.compactIdentity_deriv_eq_one
#print axioms BilevelLowerBound.norm_softProjection_lt
#print axioms BilevelLowerBound.pseudoHuber_nonneg
#print axioms BilevelLowerBound.compensatedBlock_cancels
#print axioms BilevelLowerBound.compensatedSlice_deriv_at_frontier
#print axioms BilevelLowerBound.sampleLower_bernoulli_population
#print axioms BilevelLowerBound.populationLower_at_proposed_solution
#print axioms BilevelLowerBound.hardUpper_at_proposed_solution
#print axioms BilevelLowerBound.cutoffPrimitive_contDiff
#print axioms BilevelLowerBound.softProjection_contDiff
#print axioms BilevelLowerBound.pseudoHuber_contDiff
#print axioms BilevelLowerBound.compensatedBlock_contDiff
#print axioms BilevelLowerBound.compensatedScalar_nonneg
#print axioms BilevelLowerBound.compensatedScalar_eq_zero_iff
#print axioms BilevelLowerBound.populationLower_minimum
#print axioms BilevelLowerBound.populationLower_unique_minimizer
#print axioms BilevelLowerBound.frontierExtractor_scaling
#print axioms BilevelLowerBound.visibleChain_scaling
#print axioms BilevelLowerBound.norm_iteratedFDeriv_frontierExtractor_comp_le
#print axioms BilevelLowerBound.iteratedFDeriv_clm_sub_const_eq_zero
#print axioms BilevelLowerBound.fderiv_affineRemainder_self
#print axioms BilevelLowerBound.iteratedFDeriv_affineRemainder_eq
#print axioms BilevelLowerBound.norm_iteratedFDeriv_comp_le_affine_remainder
#print axioms BilevelLowerBound.norm_iteratedFDeriv_scaledChain_one_le
#print axioms BilevelLowerBound.exists_visibleChain_base_bounds
#print axioms BilevelLowerBound.norm_iteratedFDeriv_visibleChain_comp_le
#print axioms BilevelLowerBound.norm_iteratedFDeriv_visibleChain_comp_one_le
#print axioms BilevelLowerBound.fderiv_softScale
#print axioms BilevelLowerBound.iteratedFDeriv_softScale_two_apply
#print axioms BilevelLowerBound.iteratedFDeriv_softScale_three_apply
#print axioms BilevelLowerBound.norm_fderiv_softProjection_le_one
#print axioms BilevelLowerBound.norm_iteratedFDeriv_softProjection_two_le
#print axioms BilevelLowerBound.norm_iteratedFDeriv_softProjection_three_le
#print axioms BilevelLowerBound.norm_iteratedFDeriv_normalizedHiddenProbe_le_inv_pow
#print axioms BilevelLowerBound.exists_frontier_hidden_composition_scales
#print axioms BilevelLowerBound.exists_visible_hidden_composition_scales
#print axioms BilevelLowerBound.exists_common_bound_compactIdentity_one_three
#print axioms BilevelLowerBound.norm_iteratedFDeriv_compactIdentity_le
#print axioms BilevelLowerBound.compensatedPair_second_third_bounds
#print axioms BilevelLowerBound.exists_hard_compensated_pair_regularities
#print axioms BilevelLowerBound.diagonal_hessian_lower_bound_of_perturbation
#print axioms BilevelLowerBound.exists_hard_lower_strong_convexity_certificate
#print axioms BilevelLowerBound.max_sqrt_sum_sq_equivalence
#print axioms BilevelLowerBound.fderiv_lipschitz_of_second_bound
#print axioms BilevelLowerBound.hessian_lipschitz_of_third_bound
#print axioms BilevelLowerBound.norm_iteratedFDeriv_add_le
#print axioms BilevelLowerBound.upperPopulationSum_second_bound
#print axioms BilevelLowerBound.upperPopulationSum_gradient_lipschitz
#print axioms BilevelLowerBound.lowerPopulationSum_second_bound
#print axioms BilevelLowerBound.lowerPopulationSum_third_bound
#print axioms BilevelLowerBound.lowerPopulationSum_gradient_lipschitz
#print axioms BilevelLowerBound.lowerPopulationSum_hessian_lipschitz
#print axioms BilevelLowerBound.lowerPopulationSum_strong_hessian_certificate
#print axioms BilevelLowerBound.eta_mul_sqrt_le_sqrt_div_of_gap
#print axioms BilevelLowerBound.first_derivative_bound_of_gap
#print axioms BilevelLowerBound.lower_condition_number_sandwich
#print axioms BilevelLowerBound.norm_iteratedFDeriv_pseudoHuber_two_le
#print axioms BilevelLowerBound.exists_cutoffPrimitive_second_bound
#print axioms BilevelLowerBound.norm_iteratedFDeriv_fullBaseQuadratic_two_le_five
#print axioms BilevelLowerBound.iteratedFDeriv_fullBaseQuadratic_three_eq_zero
#print axioms BilevelLowerBound.fullPopulationLower_apply
#print axioms BilevelLowerBound.exists_fullPopulationLower_regularities
#print axioms BilevelLowerBound.fullHardUpper_apply
#print axioms BilevelLowerBound.exists_fullHardUpper_second_regularities
#print axioms BilevelLowerBound.iteratedFDeriv_lowerBaseSlice_two_apply
#print axioms BilevelLowerBound.lowerBaseSlice_coercive
#print axioms BilevelLowerBound.norm_constantChainVector
#print axioms BilevelLowerBound.hiddenProbe_fullProgressWitness_progress
#print axioms BilevelLowerBound.eventually_hardFrontierMap_eq_zero_at_fullProgressWitness
#print axioms BilevelLowerBound.iteratedFDeriv_compensatedPair_two_eq_zero_at_fullProgressWitness
#print axioms BilevelLowerBound.hardLowerSlice_flat_witness_hessian
#print axioms BilevelLowerBound.exists_hardLowerSlice_certificates
#print axioms BilevelLowerBound.rightInverse_image_constant_one_ne_zero
#print axioms BilevelLowerBound.exists_hardLower_condition_number_comparison
#print axioms BilevelLowerBound.hiddenFrameTranspose_comp_frame
#print axioms BilevelLowerBound.norm_hiddenFrameTranspose_le
#print axioms BilevelLowerBound.exists_orthonormalFrame_hardLower_condition_number_comparison
#print axioms BilevelLowerBound.bernoulliAverage_importanceSample
#print axioms BilevelLowerBound.bernoulliSquaredNoise_importanceSample
#print axioms BilevelLowerBound.bernoulliSquaredNoise_importanceSample_le
#print axioms BilevelLowerBound.revealProbability_pos
#print axioms BilevelLowerBound.revealProbability_variance_le
#print axioms BilevelLowerBound.one_div_revealProbability
#print axioms BilevelLowerBound.compensatedPair_first_bound
#print axioms BilevelLowerBound.exists_hard_compensatedPair_first_bound
#print axioms BilevelLowerBound.fderiv_fullSampleLower
#print axioms BilevelLowerBound.fullSampleLower_bernoulli_gradient_unbiased
#print axioms BilevelLowerBound.exists_fullSampleLower_oracle_properties
#print axioms BilevelLowerBound.norm_lowerEuclideanToProduct_le_one
#print axioms BilevelLowerBound.exists_compensatedPairEuclidean_gradient_bound
#print axioms BilevelLowerBound.norm_fullEuclideanFrontierGradient
#print axioms BilevelLowerBound.exists_euclidean_frontier_oracle_properties
#print axioms BilevelLowerBound.FreshBernoulliEvent.condExp_bernoulliBit
#print axioms BilevelLowerBound.FreshBernoulliEvent.condExp_bernoulliSelect
#print axioms BilevelLowerBound.FreshBernoulliEvent.condExp_freshImportanceResponse
#print axioms BilevelLowerBound.norm_sq_importanceSample_sub_population
#print axioms BilevelLowerBound.FreshBernoulliEvent.condExp_freshImportanceSquaredNoise
#print axioms BilevelLowerBound.visibleChain_truncate_of_progress_le
#print axioms BilevelLowerBound.iteratedFDeriv_visibleChain_strict_cylinder
#print axioms BilevelLowerBound.iteratedFDeriv_visibleChain_cylinder_of_progress_le
#print axioms BilevelLowerBound.pullback_visibleChain_eq_prefix
#print axioms BilevelLowerBound.frontier_value_derivative_eq_prefix
#print axioms BilevelLowerBound.failedHiddenResponse_eq_prefix
#print axioms BilevelLowerBound.successfulHiddenResponse_eq_prefix
#print axioms BilevelLowerBound.failedPrefixResponse_measurable
#print axioms BilevelLowerBound.successfulPrefixResponse_measurable
#print axioms BilevelLowerBound.fderiv_compensatedPair_eq_fromJet
#print axioms BilevelLowerBound.fderiv_fullHardUpper_as_assembled
#print axioms BilevelLowerBound.hardJointGradientResponse_failed
#print axioms BilevelLowerBound.hardJointGradientResponse_successful
#print axioms BilevelLowerBound.failedHardPrefixMap_measurable
#print axioms BilevelLowerBound.successfulHardPrefixMap_measurable
#print axioms BilevelLowerBound.hardJointGradientResponse_failed_eq_prefix
#print axioms BilevelLowerBound.hardJointGradientResponse_successful_eq_prefix
#print axioms BilevelLowerBound.exposedPrefix_succ
#print axioms BilevelLowerBound.exposedPrefix_mono
#print axioms BilevelLowerBound.measurable_recursiveProcess
#print axioms BilevelLowerBound.recursiveProcess_agree_of_good
#print axioms BilevelLowerBound.residualProbe_mem_orthogonal
#print axioms BilevelLowerBound.norm_residualProbe_le
#print axioms BilevelLowerBound.norm_sum_smul_orthonormal
#print axioms BilevelLowerBound.hiddenCoordinate_le_quarter_of_no_cap
#print axioms BilevelLowerBound.progress_quarter_le_of_hidden_coordinates
#print axioms BilevelLowerBound.sum_cap_event_count_le
#print axioms BilevelLowerBound.card_paddedCapIndex
#print axioms BilevelLowerBound.ConditionalEventBound.measureReal_le
#print axioms BilevelLowerBound.measureReal_iUnion_le_card_mul
#print axioms BilevelLowerBound.measureReal_failure_le_of_conditional_cap_union
#print axioms BilevelLowerBound.measureReal_good_ge_one_sub_of_conditional_cap_union
#print axioms BilevelLowerBound.adaptiveHaarConnection
#print axioms BilevelLowerBound.capThreshold_sq
#print axioms BilevelLowerBound.capProbability_le_of_dimension_choice
#print axioms BilevelLowerBound.log_two_mul_div_nonneg
#print axioms BilevelLowerBound.haarRadius_sq
#print axioms BilevelLowerBound.two_mul_div_one_eighth
#print axioms BilevelLowerBound.successCountReal_eq_sum_bernoulliBit
#print axioms BilevelLowerBound.measurable_successCountReal
#print axioms BilevelLowerBound.FreshBernoulliEvent.integral_bernoulliBit
#print axioms BilevelLowerBound.integral_successCountReal_eq
#print axioms BilevelLowerBound.measureReal_successCountNat_ge_le
#print axioms BilevelLowerBound.measureReal_inter_ge_one_sub_add
#print axioms BilevelLowerBound.outputProgress_lt_of_haar_and_few_successes
#print axioms BilevelLowerBound.output_unfinished_probability
#print axioms BilevelLowerBound.norm_inv_smul_softProjection_le
#print axioms BilevelLowerBound.norm_inv_smul_softProjection_le_haarRadius
#print axioms BilevelLowerBound.exists_unscaled_frontier_of_progress_quarter_lt
#print axioms BilevelLowerBound.norm_fderiv_softProjection_le_softScale
#print axioms BilevelLowerBound.gradient_normalizedHardObjective
#print axioms BilevelLowerBound.norm_normalizedHardGradient_gt_half
#print axioms BilevelLowerBound.hardHyperObjective_eq_normalized
#print axioms BilevelLowerBound.gradient_hardHyperObjective
#print axioms BilevelLowerBound.norm_gradient_hardHyperObjective_gt
#print axioms BilevelLowerBound.hardHyperObjective_initial_gap
#print axioms BilevelLowerBound.finalChainScale_ge_thirtyTwo
#print axioms BilevelLowerBound.final_parameters_basic
#print axioms BilevelLowerBound.final_initial_gap_le_half
#print axioms BilevelLowerBound.final_amplified_gradient_scale
#print axioms BilevelLowerBound.max_one_div_comparison
#print axioms BilevelLowerBound.final_T_over_p_main_scale
#print axioms BilevelLowerBound.final_call_budget_implies_progress_condition
#print axioms BilevelLowerBound.exists_dimension_choice
#print axioms BilevelLowerBound.integral_ge_three_halves_of_good_event
#print axioms BilevelLowerBound.exists_fixed_frame_of_joint_good_event
#print axioms BilevelLowerBound.exists_fixed_hard_frame_of_unfinished_probability

assert_no_sorry BilevelLowerBound.progress_le_iff
assert_no_sorry BilevelLowerBound.abs_le_threshold_of_progress_le
assert_no_sorry BilevelLowerBound.progress_le_of_tail_bound
assert_no_sorry BilevelLowerBound.progress_anti_threshold
assert_no_sorry BilevelLowerBound.progress_quarter_rescaling
assert_no_sorry BilevelLowerBound.extendQuery_ignores_gifted_information
assert_no_sorry BilevelLowerBound.extendOutput_ignores_gifted_information
assert_no_sorry BilevelLowerBound.chainQ_eq_zero_of_abs_left_le_half
assert_no_sorry BilevelLowerBound.chainQ_neg_neg
assert_no_sorry BilevelLowerBound.scaledChain_eq_link_sum
assert_no_sorry BilevelLowerBound.chainQ_normalized_eq_zero
assert_no_sorry BilevelLowerBound.gaussianKernel_integrable
assert_no_sorry BilevelLowerBound.phiZero_hasDerivAt
assert_no_sorry BilevelLowerBound.phiZero_contDiff
assert_no_sorry BilevelLowerBound.psi_le_exp_one
assert_no_sorry BilevelLowerBound.phiZero_deriv_le_sqrt_exp
assert_no_sorry BilevelLowerBound.abs_chainQ_le
assert_no_sorry BilevelLowerBound.scaledChain_gap_pointwise
assert_no_sorry BilevelLowerBound.scaledChain_initial_gap
assert_no_sorry BilevelLowerBound.expNegInvSqGlue_contDiff
assert_no_sorry BilevelLowerBound.expNegInvSqGlue_iteratedDeriv_zero
assert_no_sorry BilevelLowerBound.psi_contDiff
assert_no_sorry BilevelLowerBound.psi_iteratedDeriv_eq_zero_of_le_half
assert_no_sorry BilevelLowerBound.chainQ_contDiff
assert_no_sorry BilevelLowerBound.iteratedFDeriv_chainQ_eq_zero_of_abs_fst_le_half
assert_no_sorry BilevelLowerBound.unscaledChain_contDiff
assert_no_sorry BilevelLowerBound.scaledChain_contDiff
assert_no_sorry BilevelLowerBound.iteratedFDeriv_scaledChain
assert_no_sorry BilevelLowerBound.iteratedFDeriv_scaledChain_three
assert_no_sorry BilevelLowerBound.abs_psi_deriv_le
assert_no_sorry BilevelLowerBound.chainQ_deriv_snd_le_neg_one
assert_no_sorry BilevelLowerBound.abs_unscaledChain_gradient_coordinate_lt_twentyThree
assert_no_sorry BilevelLowerBound.norm_unscaledChain_gradient_le
assert_no_sorry BilevelLowerBound.abs_scaledChain_gradient_coordinate_le
assert_no_sorry BilevelLowerBound.norm_scaledChain_gradient_le
assert_no_sorry BilevelLowerBound.scaledChain_frontier_gradient_le
assert_no_sorry BilevelLowerBound.exists_bound_psi_iteratedFDeriv
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_phiZero_le_five
assert_no_sorry BilevelLowerBound.exists_common_bound_chainQ_three
assert_no_sorry BilevelLowerBound.sum_linkDirection_norm_mul_le
assert_no_sorry BilevelLowerBound.sum_linkDirection_norm_triple_le
assert_no_sorry BilevelLowerBound.exists_unscaledChain_second_bound
assert_no_sorry BilevelLowerBound.exists_unscaledChain_third_bound
assert_no_sorry BilevelLowerBound.exists_scaledChain_second_bound
assert_no_sorry BilevelLowerBound.exists_scaledChain_third_bound
assert_no_sorry BilevelLowerBound.coordinateGate_eq_transition_abs
assert_no_sorry BilevelLowerBound.frontierSummand_nonzero_index
assert_no_sorry BilevelLowerBound.frontierExtractor_eq_zero_of_full_progress
assert_no_sorry BilevelLowerBound.abs_frontierExtractor_le
assert_no_sorry BilevelLowerBound.frontierExtractor_progress_cylinder
assert_no_sorry BilevelLowerBound.frontierLinkGate_contDiff
assert_no_sorry BilevelLowerBound.frontierExtractor_contDiff
assert_no_sorry BilevelLowerBound.iteratedFDeriv_frontierExtractor_strict_cylinder
assert_no_sorry BilevelLowerBound.iteratedFDeriv_frontierExtractor_progress_cylinder
assert_no_sorry BilevelLowerBound.iteratedFDeriv_frontierSummand_zero_unless_frontier
assert_no_sorry BilevelLowerBound.iteratedFDeriv_frontierExtractor_eq_frontier_summand
assert_no_sorry BilevelLowerBound.iteratedFDeriv_frontierExtractor_eq_zero_of_full_progress
assert_no_sorry BilevelLowerBound.exists_common_bound_frontierTransition_three
assert_no_sorry BilevelLowerBound.exists_common_bound_coordinateGate_three
assert_no_sorry BilevelLowerBound.frontierRadialProfile_contDiff
assert_no_sorry BilevelLowerBound.frontierLinkGate_eq_radialProfile_norm_sq
assert_no_sorry BilevelLowerBound.tailActivationNormSq_contDiff
assert_no_sorry BilevelLowerBound.frontierLinkGate_eq_radialProfile_comp_tailActivationNormSq
assert_no_sorry BilevelLowerBound.iteratedFDeriv_frontierRadialProfile_eq_zero_of_nine_sixteenths_lt
assert_no_sorry BilevelLowerBound.exists_common_bound_frontierRadialProfile_three
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_chainLink_le
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_mul_scaled_le_eight
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_frontierExtractor_le_of_gate_bound
assert_no_sorry BilevelLowerBound.iteratedFDeriv_tailActivation_apply
assert_no_sorry BilevelLowerBound.sum_coordinate_product_sq_le
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_tailActivation_le
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_tailActivationNormSq_le_of_norm
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_frontierLinkGate_le
assert_no_sorry BilevelLowerBound.exists_common_bound_frontierLinkGate_three
assert_no_sorry BilevelLowerBound.exists_common_bound_frontierExtractor_three
assert_no_sorry BilevelLowerBound.cutoffWeight_deriv_eq_zero_of_abs_le_one
assert_no_sorry BilevelLowerBound.compactIdentity_deriv_eq_one
assert_no_sorry BilevelLowerBound.norm_softProjection_lt
assert_no_sorry BilevelLowerBound.pseudoHuber_nonneg
assert_no_sorry BilevelLowerBound.compensatedBlock_cancels
assert_no_sorry BilevelLowerBound.compensatedSlice_deriv_at_frontier
assert_no_sorry BilevelLowerBound.sampleLower_bernoulli_population
assert_no_sorry BilevelLowerBound.populationLower_at_proposed_solution
assert_no_sorry BilevelLowerBound.hardUpper_at_proposed_solution
assert_no_sorry BilevelLowerBound.cutoffPrimitive_contDiff
assert_no_sorry BilevelLowerBound.softProjection_contDiff
assert_no_sorry BilevelLowerBound.pseudoHuber_contDiff
assert_no_sorry BilevelLowerBound.compensatedBlock_contDiff
assert_no_sorry BilevelLowerBound.compensatedScalar_nonneg
assert_no_sorry BilevelLowerBound.compensatedScalar_eq_zero_iff
assert_no_sorry BilevelLowerBound.populationLower_minimum
assert_no_sorry BilevelLowerBound.populationLower_unique_minimizer
assert_no_sorry BilevelLowerBound.frontierExtractor_scaling
assert_no_sorry BilevelLowerBound.visibleChain_scaling
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_frontierExtractor_comp_le
assert_no_sorry BilevelLowerBound.iteratedFDeriv_clm_sub_const_eq_zero
assert_no_sorry BilevelLowerBound.fderiv_affineRemainder_self
assert_no_sorry BilevelLowerBound.iteratedFDeriv_affineRemainder_eq
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_comp_le_affine_remainder
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_scaledChain_one_le
assert_no_sorry BilevelLowerBound.exists_visibleChain_base_bounds
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_visibleChain_comp_le
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_visibleChain_comp_one_le
assert_no_sorry BilevelLowerBound.fderiv_softScale
assert_no_sorry BilevelLowerBound.iteratedFDeriv_softScale_two_apply
assert_no_sorry BilevelLowerBound.iteratedFDeriv_softScale_three_apply
assert_no_sorry BilevelLowerBound.norm_fderiv_softProjection_le_one
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_softProjection_two_le
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_softProjection_three_le
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_normalizedHiddenProbe_le_inv_pow
assert_no_sorry BilevelLowerBound.exists_frontier_hidden_composition_scales
assert_no_sorry BilevelLowerBound.exists_visible_hidden_composition_scales
assert_no_sorry BilevelLowerBound.exists_common_bound_compactIdentity_one_three
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_compactIdentity_le
assert_no_sorry BilevelLowerBound.compensatedPair_second_third_bounds
assert_no_sorry BilevelLowerBound.exists_hard_compensated_pair_regularities
assert_no_sorry BilevelLowerBound.diagonal_hessian_lower_bound_of_perturbation
assert_no_sorry BilevelLowerBound.exists_hard_lower_strong_convexity_certificate
assert_no_sorry BilevelLowerBound.max_sqrt_sum_sq_equivalence
assert_no_sorry BilevelLowerBound.fderiv_lipschitz_of_second_bound
assert_no_sorry BilevelLowerBound.hessian_lipschitz_of_third_bound
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_add_le
assert_no_sorry BilevelLowerBound.upperPopulationSum_second_bound
assert_no_sorry BilevelLowerBound.upperPopulationSum_gradient_lipschitz
assert_no_sorry BilevelLowerBound.lowerPopulationSum_second_bound
assert_no_sorry BilevelLowerBound.lowerPopulationSum_third_bound
assert_no_sorry BilevelLowerBound.lowerPopulationSum_gradient_lipschitz
assert_no_sorry BilevelLowerBound.lowerPopulationSum_hessian_lipschitz
assert_no_sorry BilevelLowerBound.lowerPopulationSum_strong_hessian_certificate
assert_no_sorry BilevelLowerBound.eta_mul_sqrt_le_sqrt_div_of_gap
assert_no_sorry BilevelLowerBound.first_derivative_bound_of_gap
assert_no_sorry BilevelLowerBound.lower_condition_number_sandwich
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_pseudoHuber_two_le
assert_no_sorry BilevelLowerBound.exists_cutoffPrimitive_second_bound
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_fullBaseQuadratic_two_le_five
assert_no_sorry BilevelLowerBound.iteratedFDeriv_fullBaseQuadratic_three_eq_zero
assert_no_sorry BilevelLowerBound.fullPopulationLower_apply
assert_no_sorry BilevelLowerBound.exists_fullPopulationLower_regularities
assert_no_sorry BilevelLowerBound.fullHardUpper_apply
assert_no_sorry BilevelLowerBound.exists_fullHardUpper_second_regularities
assert_no_sorry BilevelLowerBound.iteratedFDeriv_lowerBaseSlice_two_apply
assert_no_sorry BilevelLowerBound.lowerBaseSlice_coercive
assert_no_sorry BilevelLowerBound.norm_constantChainVector
assert_no_sorry BilevelLowerBound.hiddenProbe_fullProgressWitness_progress
assert_no_sorry BilevelLowerBound.eventually_hardFrontierMap_eq_zero_at_fullProgressWitness
assert_no_sorry BilevelLowerBound.iteratedFDeriv_compensatedPair_two_eq_zero_at_fullProgressWitness
assert_no_sorry BilevelLowerBound.hardLowerSlice_flat_witness_hessian
assert_no_sorry BilevelLowerBound.exists_hardLowerSlice_certificates
assert_no_sorry BilevelLowerBound.rightInverse_image_constant_one_ne_zero
assert_no_sorry BilevelLowerBound.exists_hardLower_condition_number_comparison
assert_no_sorry BilevelLowerBound.hiddenFrameTranspose_comp_frame
assert_no_sorry BilevelLowerBound.norm_hiddenFrameTranspose_le
assert_no_sorry BilevelLowerBound.exists_orthonormalFrame_hardLower_condition_number_comparison
assert_no_sorry BilevelLowerBound.bernoulliAverage_importanceSample
assert_no_sorry BilevelLowerBound.bernoulliSquaredNoise_importanceSample
assert_no_sorry BilevelLowerBound.bernoulliSquaredNoise_importanceSample_le
assert_no_sorry BilevelLowerBound.revealProbability_pos
assert_no_sorry BilevelLowerBound.revealProbability_variance_le
assert_no_sorry BilevelLowerBound.one_div_revealProbability
assert_no_sorry BilevelLowerBound.compensatedPair_first_bound
assert_no_sorry BilevelLowerBound.exists_hard_compensatedPair_first_bound
assert_no_sorry BilevelLowerBound.fderiv_fullSampleLower
assert_no_sorry BilevelLowerBound.fullSampleLower_bernoulli_gradient_unbiased
assert_no_sorry BilevelLowerBound.exists_fullSampleLower_oracle_properties
assert_no_sorry BilevelLowerBound.norm_lowerEuclideanToProduct_le_one
assert_no_sorry BilevelLowerBound.exists_compensatedPairEuclidean_gradient_bound
assert_no_sorry BilevelLowerBound.norm_fullEuclideanFrontierGradient
assert_no_sorry BilevelLowerBound.exists_euclidean_frontier_oracle_properties
assert_no_sorry BilevelLowerBound.FreshBernoulliEvent.condExp_bernoulliBit
assert_no_sorry BilevelLowerBound.FreshBernoulliEvent.condExp_bernoulliSelect
assert_no_sorry BilevelLowerBound.FreshBernoulliEvent.condExp_freshImportanceResponse
assert_no_sorry BilevelLowerBound.norm_sq_importanceSample_sub_population
assert_no_sorry BilevelLowerBound.FreshBernoulliEvent.condExp_freshImportanceSquaredNoise
assert_no_sorry BilevelLowerBound.visibleChain_truncate_of_progress_le
assert_no_sorry BilevelLowerBound.iteratedFDeriv_visibleChain_strict_cylinder
assert_no_sorry BilevelLowerBound.iteratedFDeriv_visibleChain_cylinder_of_progress_le
assert_no_sorry BilevelLowerBound.pullback_visibleChain_eq_prefix
assert_no_sorry BilevelLowerBound.frontier_value_derivative_eq_prefix
assert_no_sorry BilevelLowerBound.failedHiddenResponse_eq_prefix
assert_no_sorry BilevelLowerBound.successfulHiddenResponse_eq_prefix
assert_no_sorry BilevelLowerBound.failedPrefixResponse_measurable
assert_no_sorry BilevelLowerBound.successfulPrefixResponse_measurable
assert_no_sorry BilevelLowerBound.fderiv_compensatedPair_eq_fromJet
assert_no_sorry BilevelLowerBound.fderiv_fullHardUpper_as_assembled
assert_no_sorry BilevelLowerBound.hardJointGradientResponse_failed
assert_no_sorry BilevelLowerBound.hardJointGradientResponse_successful
assert_no_sorry BilevelLowerBound.failedHardPrefixMap_measurable
assert_no_sorry BilevelLowerBound.successfulHardPrefixMap_measurable
assert_no_sorry BilevelLowerBound.hardJointGradientResponse_failed_eq_prefix
assert_no_sorry BilevelLowerBound.hardJointGradientResponse_successful_eq_prefix
assert_no_sorry BilevelLowerBound.exposedPrefix_succ
assert_no_sorry BilevelLowerBound.exposedPrefix_mono
assert_no_sorry BilevelLowerBound.measurable_recursiveProcess
assert_no_sorry BilevelLowerBound.recursiveProcess_agree_of_good
assert_no_sorry BilevelLowerBound.residualProbe_mem_orthogonal
assert_no_sorry BilevelLowerBound.norm_residualProbe_le
assert_no_sorry BilevelLowerBound.norm_sum_smul_orthonormal
assert_no_sorry BilevelLowerBound.hiddenCoordinate_le_quarter_of_no_cap
assert_no_sorry BilevelLowerBound.progress_quarter_le_of_hidden_coordinates
assert_no_sorry BilevelLowerBound.sum_cap_event_count_le
assert_no_sorry BilevelLowerBound.card_paddedCapIndex
assert_no_sorry BilevelLowerBound.ConditionalEventBound.measureReal_le
assert_no_sorry BilevelLowerBound.measureReal_iUnion_le_card_mul
assert_no_sorry BilevelLowerBound.measureReal_failure_le_of_conditional_cap_union
assert_no_sorry BilevelLowerBound.measureReal_good_ge_one_sub_of_conditional_cap_union
assert_no_sorry BilevelLowerBound.adaptiveHaarConnection
assert_no_sorry BilevelLowerBound.capThreshold_sq
assert_no_sorry BilevelLowerBound.capProbability_le_of_dimension_choice
assert_no_sorry BilevelLowerBound.log_two_mul_div_nonneg
assert_no_sorry BilevelLowerBound.haarRadius_sq
assert_no_sorry BilevelLowerBound.two_mul_div_one_eighth
assert_no_sorry BilevelLowerBound.successCountReal_eq_sum_bernoulliBit
assert_no_sorry BilevelLowerBound.measurable_successCountReal
assert_no_sorry BilevelLowerBound.FreshBernoulliEvent.integral_bernoulliBit
assert_no_sorry BilevelLowerBound.integral_successCountReal_eq
assert_no_sorry BilevelLowerBound.measureReal_successCountNat_ge_le
assert_no_sorry BilevelLowerBound.measureReal_inter_ge_one_sub_add
assert_no_sorry BilevelLowerBound.outputProgress_lt_of_haar_and_few_successes
assert_no_sorry BilevelLowerBound.output_unfinished_probability
assert_no_sorry BilevelLowerBound.norm_inv_smul_softProjection_le
assert_no_sorry BilevelLowerBound.norm_inv_smul_softProjection_le_haarRadius
assert_no_sorry BilevelLowerBound.exists_unscaled_frontier_of_progress_quarter_lt
assert_no_sorry BilevelLowerBound.norm_fderiv_softProjection_le_softScale
assert_no_sorry BilevelLowerBound.gradient_normalizedHardObjective
assert_no_sorry BilevelLowerBound.norm_normalizedHardGradient_gt_half
assert_no_sorry BilevelLowerBound.hardHyperObjective_eq_normalized
assert_no_sorry BilevelLowerBound.gradient_hardHyperObjective
assert_no_sorry BilevelLowerBound.norm_gradient_hardHyperObjective_gt
assert_no_sorry BilevelLowerBound.hardHyperObjective_initial_gap
assert_no_sorry BilevelLowerBound.finalChainScale_ge_thirtyTwo
assert_no_sorry BilevelLowerBound.final_parameters_basic
assert_no_sorry BilevelLowerBound.final_initial_gap_le_half
assert_no_sorry BilevelLowerBound.final_amplified_gradient_scale
assert_no_sorry BilevelLowerBound.max_one_div_comparison
assert_no_sorry BilevelLowerBound.final_T_over_p_main_scale
assert_no_sorry BilevelLowerBound.final_call_budget_implies_progress_condition
assert_no_sorry BilevelLowerBound.exists_dimension_choice
assert_no_sorry BilevelLowerBound.integral_ge_three_halves_of_good_event
assert_no_sorry BilevelLowerBound.exists_fixed_frame_of_joint_good_event
assert_no_sorry BilevelLowerBound.exists_fixed_hard_frame_of_unfinished_probability

#print axioms BilevelLowerBound.hardHyperObjective_initial_gap_le_chainGapConstant
#print axioms BilevelLowerBound.final_scale_implies_regularities
#print axioms BilevelLowerBound.condition_number_scale_comparison
#print axioms BilevelLowerBound.condition_number_call_budget_transfer
#print axioms BilevelLowerBound.condition_number_scale_sandwich
#print axioms BilevelLowerBound.exists_main_scalar_constants
#print axioms BilevelLowerBound.exists_final_scale_condition_number_comparison
#print axioms BilevelLowerBound.exists_fixed_section_of_product_event
#print axioms BilevelLowerBound.moment_failure_of_large_event
#print axioms BilevelLowerBound.final_parameter_dimension_certificate
#print axioms BilevelLowerBound.main_lower_bound_assembly
#print axioms BilevelLowerBound.fullyQuantifiedLowerBound_of_certified_realizer
#print axioms BilevelLowerBound.fullyQuantifiedLowerBound_of_dimension_certificate
#print axioms BilevelLowerBound.certifiedHardInstance_mk

assert_no_sorry BilevelLowerBound.hardHyperObjective_initial_gap_le_chainGapConstant
assert_no_sorry BilevelLowerBound.final_scale_implies_regularities
assert_no_sorry BilevelLowerBound.condition_number_scale_comparison
assert_no_sorry BilevelLowerBound.condition_number_call_budget_transfer
assert_no_sorry BilevelLowerBound.condition_number_scale_sandwich
assert_no_sorry BilevelLowerBound.exists_main_scalar_constants
assert_no_sorry BilevelLowerBound.exists_final_scale_condition_number_comparison
assert_no_sorry BilevelLowerBound.exists_fixed_section_of_product_event
assert_no_sorry BilevelLowerBound.moment_failure_of_large_event
assert_no_sorry BilevelLowerBound.final_parameter_dimension_certificate
assert_no_sorry BilevelLowerBound.main_lower_bound_assembly
assert_no_sorry BilevelLowerBound.fullyQuantifiedLowerBound_of_certified_realizer
assert_no_sorry BilevelLowerBound.fullyQuantifiedLowerBound_of_dimension_certificate
assert_no_sorry BilevelLowerBound.certifiedHardInstance_mk

/-! ## Paper-level concrete completion layer -/

#print axioms BilevelLowerBound.norm_normalizedHardGradient_le
#print axioms BilevelLowerBound.hardHyperGradient_moments_integrable
#print axioms BilevelLowerBound.main_lower_bound_expectation_from_residual_geometry
#print axioms BilevelLowerBound.exists_sharp_lower_hessian_modulus
#print axioms BilevelLowerBound.exists_sharp_lower_hessian_upper_bound
#print axioms BilevelLowerBound.exists_orthonormalFrame_sharp_lower_constants
#print axioms BilevelLowerBound.paperRunTranscript_succ
#print axioms BilevelLowerBound.length_paperRunTranscript
#print axioms BilevelLowerBound.get_paperRunTranscript_succ_last
#print axioms BilevelLowerBound.exists_simultaneous_paper_hard_certificates
#print axioms BilevelLowerBound.paper_main_for_one_algorithm
#print axioms BilevelLowerBound.PaperPopulationClassMember.to_final_uniform_bounds
#print axioms BilevelLowerBound.PaperPopulationClassMember.muG_le_muGAct
#print axioms BilevelLowerBound.paper_failure_for_one_algorithm
#print axioms BilevelLowerBound.concrete_paper_main_theorem

assert_no_sorry BilevelLowerBound.norm_normalizedHardGradient_le
assert_no_sorry BilevelLowerBound.hardHyperGradient_moments_integrable
assert_no_sorry BilevelLowerBound.main_lower_bound_expectation_from_residual_geometry
assert_no_sorry BilevelLowerBound.exists_sharp_lower_hessian_modulus
assert_no_sorry BilevelLowerBound.exists_sharp_lower_hessian_upper_bound
assert_no_sorry BilevelLowerBound.exists_orthonormalFrame_sharp_lower_constants
assert_no_sorry BilevelLowerBound.paperRunTranscript_succ
assert_no_sorry BilevelLowerBound.length_paperRunTranscript
assert_no_sorry BilevelLowerBound.get_paperRunTranscript_succ_last
assert_no_sorry BilevelLowerBound.exists_simultaneous_paper_hard_certificates
assert_no_sorry BilevelLowerBound.paper_main_for_one_algorithm
assert_no_sorry BilevelLowerBound.PaperPopulationClassMember.to_final_uniform_bounds
assert_no_sorry BilevelLowerBound.PaperPopulationClassMember.muG_le_muGAct
assert_no_sorry BilevelLowerBound.paper_failure_for_one_algorithm
assert_no_sorry BilevelLowerBound.concrete_paper_main_theorem
