/-
Copyright (c) 2026 Zhihao Gu, Qilong Wu, and Junchi Yang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zhihao Gu, Qilong Wu, Junchi Yang
-/
import BilevelLowerBoundLean.Interface

/-!
# Assembly of the concrete hard-oracle response

The analytic interface records only the hidden visible covector and, on a
successful call, the value and covector of the frontier.  Here we prove that
these data assemble to the exact derivatives of the paper's upper and sample
lower objectives.  Thus the prefix identities in `Interface` apply to the
complete joint stochastic first-order response, not merely to an abstract
surrogate.
-/

open scoped ContDiff Topology

namespace BilevelLowerBound

noncomputable section

/-- First derivative of the compensated block reconstructed from the value
and derivative of `theta` at the queried lower point. -/
def compensatedDerivativeFromJet
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (η v θ : ℝ) (dθ : E →L[ℝ] ℝ) : (E × ℝ) →L[ℝ] ℝ :=
  (θ - compactIdentity η v) •
      dθ.comp (ContinuousLinearMap.fst ℝ E ℝ) -
    θ • (fderiv ℝ (compactIdentity η) v).comp
      (ContinuousLinearMap.snd ℝ E ℝ)

/-- The derivative of the compensated block depends only on the first jet of
the hidden frontier at the queried point. -/
theorem fderiv_compensatedPair_eq_fromJet
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    {η : ℝ} (hη : η ≠ 0) {θfun : E → ℝ} {z : E}
    (hθ : DifferentiableAt ℝ θfun z) (v : ℝ) :
    fderiv ℝ (compensatedPair η θfun) (z, v) =
      compensatedDerivativeFromJet η v (θfun z) (fderiv ℝ θfun z) := by
  let Lz : (E × ℝ) →L[ℝ] E := ContinuousLinearMap.fst ℝ E ℝ
  let Lv : (E × ℝ) →L[ℝ] ℝ := ContinuousLinearMap.snd ℝ E ℝ
  let Theta : E × ℝ → ℝ := fun p ↦ θfun p.1
  let Psi : E × ℝ → ℝ := fun p ↦ compactIdentity η p.2
  have hTheta : HasFDerivAt Theta ((fderiv ℝ θfun z).comp Lz) (z, v) := by
    exact hθ.hasFDerivAt.comp (z, v) Lz.hasFDerivAt
  have hPsiBase : DifferentiableAt ℝ (compactIdentity η) v :=
    (compactIdentity_contDiff hη).differentiable (by norm_num) v
  have hPsi : HasFDerivAt Psi
      ((fderiv ℝ (compactIdentity η) v).comp Lv) (z, v) := by
    exact hPsiBase.hasFDerivAt.comp (z, v) Lv.hasFDerivAt
  have hHalfSquare := (hTheta.mul hTheta).const_mul (1 / 2 : ℝ)
  have hProduct := hTheta.mul hPsi
  have hDerivative := hHalfSquare.sub hProduct
  have hFun : compensatedPair η θfun =
      fun p : E × ℝ ↦ (1 / 2 : ℝ) * Theta p * Theta p -
        Theta p * Psi p := by
    funext p
    simp [compensatedPair, compensatedBlock, Theta, Psi]
    ring
  have hTarget :
      (fun p : E × ℝ ↦ (1 / 2 : ℝ) * Theta p * Theta p -
        Theta p * Psi p) =
      ((fun p : E × ℝ ↦ (1 / 2 : ℝ) * (Theta * Theta) p) -
        Theta * Psi) := by
    funext p
    simp
    ring
  rw [hFun, hTarget, hDerivative.fderiv]
  apply ContinuousLinearMap.ext
  intro w
  simp [compensatedDerivativeFromJet, Theta, Psi, Lz, Lv,
    ContinuousLinearMap.comp_apply]
  ring

/-- Hidden coordinate and derivative generated by the concrete rotated soft
probe at a query `z`. -/
def hardProbeJetAt
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {T : ℕ} (R : ℝ) (L : E →L[ℝ] ChainVector T) (z : E) :
    HiddenProbeJet E T :=
  (hiddenProbe R L z, fderiv ℝ (hiddenProbe R L) z)

/-- The visible hidden covector is exactly the derivative of the concrete
hard visible map at the paper radius. -/
theorem pullback_visibleChain_hardProbeJetAt_hardRadius
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {T : ℕ} {η : ℝ} (hη : 0 < η) (hT : 0 < T)
    (L : E →L[ℝ] ChainVector T) (z : E) :
    pullbackChainDerivative (visibleChain η)
        (hardProbeJetAt (hardRadius η T) L z) =
      fderiv ℝ (hardVisibleMap η L) z := by
  have hOuter : DifferentiableAt ℝ
      (visibleChain η : ChainVector T → ℝ)
        (hiddenProbe (hardRadius η T) L z) :=
    (visibleChain_contDiff η).differentiable (by norm_num) _
  have hInner : DifferentiableAt ℝ
      (hiddenProbe (hardRadius η T) L) z :=
    (hiddenProbe_contDiff (hardRadius_pos hη hT).ne' L)
      |>.differentiable (by norm_num) z
  exact (fderiv_comp z hOuter hInner).symm

theorem frontier_value_pullback_hardProbeJetAt_hardRadius
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {T : ℕ} {η : ℝ} (hη : 0 < η) (hT : 0 < T)
    (L : E →L[ℝ] ChainVector T) (z : E) :
    frontierExtractor η (hardProbeJetAt (hardRadius η T) L z).1 =
        hardFrontierMap η L z ∧
      pullbackChainDerivative (frontierExtractor η)
          (hardProbeJetAt (hardRadius η T) L z) =
        fderiv ℝ (hardFrontierMap η L) z := by
  constructor
  · rfl
  · have hOuter : DifferentiableAt ℝ
        (frontierExtractor η : ChainVector T → ℝ)
          (hiddenProbe (hardRadius η T) L z) :=
      (frontierExtractor_contDiff η).differentiable (by norm_num) _
    have hInner : DifferentiableAt ℝ
        (hiddenProbe (hardRadius η T) L) z :=
      (hiddenProbe_contDiff (hardRadius_pos hη hT).ne' L)
        |>.differentiable (by norm_num) z
    exact (fderiv_comp z hOuter hInner).symm

/-- Assemble the complete upper/lower derivative pair from public query data
and the sufficient hidden payload. -/
def assembleHardJointResponse
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (κ η prob ξ lam R : ℝ) (a : E × (E × ℝ))
    (payload : HiddenOracleResponse E) :
    ((E × (E × ℝ)) →L[ℝ] ℝ) ×
      ((E × (E × ℝ)) →L[ℝ] ℝ) :=
  let upper := payload.1.comp fullZProjection +
    fderiv ℝ (fullCutoffPrimitive : E × (E × ℝ) → ℝ) a +
    fderiv ℝ (fullPseudoHuber lam R) a
  let frontierLocal := compensatedDerivativeFromJet η a.2.2
    payload.2.1 payload.2.2
  let lower := fderiv ℝ (fullBaseQuadratic κ) a +
    (ξ / prob) • frontierLocal.comp fullLowerProjection
  (upper, lower)

/-- The concrete joint response returned by the hard stochastic oracle. -/
def hardJointGradientResponse
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {T : ℕ} (κ η prob ξ lam R : ℝ)
    (L : E →L[ℝ] ChainVector T) (a : E × (E × ℝ)) :
    ((E × (E × ℝ)) →L[ℝ] ℝ) ×
      ((E × (E × ℝ)) →L[ℝ] ℝ) :=
  (fderiv ℝ (fullHardUpper η lam R L) a,
    fderiv ℝ (fullSampleLower κ η prob ξ L) a)

theorem fderiv_fullHardUpper_as_assembled
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {T : ℕ} {η R : ℝ} (hη : 0 < η) (hT : 0 < T) (hR : R ≠ 0)
    (lam : ℝ) (L : E →L[ℝ] ChainVector T)
    (a : E × (E × ℝ)) :
    fderiv ℝ (fullHardUpper η lam R L) a =
      (fderiv ℝ (hardVisibleMap η L) a.2.1).comp fullZProjection +
        fderiv ℝ (fullCutoffPrimitive : E × (E × ℝ) → ℝ) a +
        fderiv ℝ (fullPseudoHuber lam R) a := by
  have hA : DifferentiableAt ℝ (fullHardVisible η L) a :=
    ((hardVisibleMap_contDiff hη hT L).comp
      (fullZProjection (E := E)).contDiff).differentiable (by norm_num) a
  have hB : DifferentiableAt ℝ
      (fullCutoffPrimitive : E × (E × ℝ) → ℝ) a :=
    (cutoffPrimitive_contDiff.comp
      (fullVProjection (E := E)).contDiff).differentiable (by norm_num) a
  have hC : DifferentiableAt ℝ (fullPseudoHuber lam R) a :=
    ((pseudoHuber_contDiff hR).comp
      (fullZProjection (E := E)).contDiff).differentiable (by norm_num) a
  have hVisible :
      fderiv ℝ (fullHardVisible η L) a =
        (fderiv ℝ (hardVisibleMap η L) a.2.1).comp fullZProjection := by
    have hProj : DifferentiableAt ℝ
        (fullZProjection : E × (E × ℝ) → E) a :=
      (fullZProjection (E := E)).differentiableAt
    have hComp := fderiv_comp a
      ((hardVisibleMap_contDiff hη hT L).differentiable (by norm_num) _)
      hProj
    simpa [fullHardVisible] using hComp
  unfold fullHardUpper upperPopulationSum
  rw [fderiv_add (hA.add hB) hC, fderiv_add hA hB, hVisible]

/-- On a failed bit, the concrete joint oracle response is assembled from a
payload containing no frontier information. -/
theorem hardJointGradientResponse_failed
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {T : ℕ} {η R prob : ℝ} (hη : 0 < η) (hT : 0 < T)
    (hR : R ≠ 0) (κ lam : ℝ) (L : E →L[ℝ] ChainVector T)
    (a : E × (E × ℝ)) :
    hardJointGradientResponse κ η prob 0 lam R L a =
      assembleHardJointResponse κ η prob 0 lam R a
        (failedHiddenResponse η
          (hardProbeJetAt (hardRadius η T) L a.2.1)) := by
  apply Prod.ext
  · rw [hardJointGradientResponse, assembleHardJointResponse]
    dsimp only
    rw [fderiv_fullHardUpper_as_assembled hη hT hR]
    simp only [failedHiddenResponse]
    rw [pullback_visibleChain_hardProbeJetAt_hardRadius hη hT]
  · rw [hardJointGradientResponse, assembleHardJointResponse]
    dsimp only
    rw [fderiv_fullSampleLower hη hT]
    simp [importanceSample, failedHiddenResponse,
      compensatedDerivativeFromJet]

/-- On a successful bit, the complete response is assembled from the visible
prefix plus the value and derivative of the single frontier. -/
theorem hardJointGradientResponse_successful
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {T : ℕ} {η R prob : ℝ} (hη : 0 < η) (hT : 0 < T)
    (hR : R ≠ 0) (κ lam : ℝ) (L : E →L[ℝ] ChainVector T)
    (a : E × (E × ℝ)) :
    hardJointGradientResponse κ η prob 1 lam R L a =
      assembleHardJointResponse κ η prob 1 lam R a
        (successfulHiddenResponse η
          (hardProbeJetAt (hardRadius η T) L a.2.1)) := by
  have hFrontier := frontier_value_pullback_hardProbeJetAt_hardRadius
    hη hT L a.2.1
  apply Prod.ext
  · rw [hardJointGradientResponse, assembleHardJointResponse]
    dsimp only
    rw [fderiv_fullHardUpper_as_assembled hη hT hR]
    simp only [successfulHiddenResponse]
    rw [pullback_visibleChain_hardProbeJetAt_hardRadius hη hT]
  · rw [hardJointGradientResponse, assembleHardJointResponse]
    dsimp only
    rw [fderiv_fullSampleLower hη hT]
    unfold importanceSample
    rw [show fderiv ℝ
        (fullCompensatedPair η (hardFrontierMap η L)) a =
          (fderiv ℝ
            (compensatedPair η (hardFrontierMap η L)) a.2).comp
              fullLowerProjection by
        have hProj : DifferentiableAt ℝ
            (fullLowerProjection : E × (E × ℝ) → E × ℝ) a :=
          (fullLowerProjection (E := E)).differentiableAt
        change fderiv ℝ
          ((compensatedPair η (hardFrontierMap η L)) ∘
            (fullLowerProjection : E × (E × ℝ) → E × ℝ)) a = _
        calc
          _ = (fderiv ℝ
                (compensatedPair η (hardFrontierMap η L))
                (fullLowerProjection a)).comp
              (fderiv ℝ
                (fullLowerProjection : E × (E × ℝ) → E × ℝ) a) :=
            fderiv_comp a
              ((compensatedPair_contDiff hη.ne'
                (hardFrontierMap_contDiff hη hT L)).differentiable
                  (by norm_num) a.2)
              hProj
          _ = _ := by
            rw [fullLowerProjection_apply,
              (fullLowerProjection (E := E)).hasFDerivAt.fderiv]]
    rw [fderiv_compensatedPair_eq_fromJet hη.ne'
      ((hardFrontierMap_contDiff hη hT L).differentiable
        (by norm_num) a.2.1)]
    simp only [successfulHiddenResponse]
    rw [hFrontier.1, hFrontier.2]

/-! ## Uniform Borel maps for the complete joint response -/

/-- Complete failed-call response map.  The input is immediately projected
to the visible prefix by `failedPrefixResponse`. -/
def failedHardPrefixMap
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {T : ℕ} (κ η prob lam R : ℝ) (a : E × (E × ℝ))
    (ell : ℕ) (data : HiddenProbeJet E T) :=
  assembleHardJointResponse κ η prob 0 lam R a
    (failedPrefixResponse η ell data)

/-- Complete successful-call response map. -/
def successfulHardPrefixMap
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {T : ℕ} (κ η prob lam R : ℝ) (a : E × (E × ℝ))
    (ell : ℕ) (data : HiddenProbeJet E T) :=
  assembleHardJointResponse κ η prob 1 lam R a
    (successfulPrefixResponse η ell data)

theorem assembleHardJointResponse_continuous
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (κ η prob ξ lam R : ℝ) (a : E × (E × ℝ)) :
    Continuous (assembleHardJointResponse κ η prob ξ lam R a) := by
  unfold assembleHardJointResponse compensatedDerivativeFromJet
  fun_prop

theorem failedHardPrefixMap_continuous
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {T : ℕ} (κ η prob lam R : ℝ) (a : E × (E × ℝ)) (ell : ℕ) :
    Continuous (failedHardPrefixMap
      (T := T) κ η prob lam R a ell) :=
  (assembleHardJointResponse_continuous κ η prob 0 lam R a).comp
    (failedPrefixResponse_continuous η)

theorem successfulHardPrefixMap_continuous
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {T : ℕ} (κ η prob lam R : ℝ) (a : E × (E × ℝ)) (ell : ℕ) :
    Continuous (successfulHardPrefixMap
      (T := T) κ η prob lam R a ell) :=
  (assembleHardJointResponse_continuous κ η prob 1 lam R a).comp
    (successfulPrefixResponse_continuous η)

theorem failedHardPrefixMap_measurable
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] [SecondCountableTopology E]
    [MeasurableSpace E] [BorelSpace E]
    {T : ℕ} (κ η prob lam R : ℝ) (a : E × (E × ℝ)) (ell : ℕ) :
    Measurable (failedHardPrefixMap
      (T := T) κ η prob lam R a ell) :=
  (failedHardPrefixMap_continuous κ η prob lam R a ell).measurable

theorem successfulHardPrefixMap_measurable
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] [SecondCountableTopology E]
    [MeasurableSpace E] [BorelSpace E]
    {T : ℕ} (κ η prob lam R : ℝ) (a : E × (E × ℝ)) (ell : ℕ) :
    Measurable (successfulHardPrefixMap
      (T := T) κ η prob lam R a ell) :=
  (successfulHardPrefixMap_continuous κ η prob lam R a ell).measurable

/-- Exact formal prefix identity for a failed concrete oracle call. -/
theorem hardJointGradientResponse_failed_eq_prefix
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {T ell : ℕ} {η R prob : ℝ} (hη : 0 < η) (hT : 0 < T)
    (hR : R ≠ 0) (κ lam : ℝ) (L : E →L[ℝ] ChainVector T)
    (a : E × (E × ℝ))
    (hprog : progress (η / 4)
      (hardProbeJetAt (hardRadius η T) L a.2.1).1 ≤ ell) :
    hardJointGradientResponse κ η prob 0 lam R L a =
      failedHardPrefixMap κ η prob lam R a ell
        (hardProbeJetAt (hardRadius η T) L a.2.1) := by
  rw [hardJointGradientResponse_failed hη hT hR]
  unfold failedHardPrefixMap
  rw [failedHiddenResponse_eq_prefix hη _ hprog]

/-- Exact formal prefix identity for a successful concrete oracle call. -/
theorem hardJointGradientResponse_successful_eq_prefix
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {T ell : ℕ} {η R prob : ℝ} (hη : 0 < η) (hT : 0 < T)
    (hR : R ≠ 0) (κ lam : ℝ) (L : E →L[ℝ] ChainVector T)
    (a : E × (E × ℝ))
    (hprog : progress (η / 4)
      (hardProbeJetAt (hardRadius η T) L a.2.1).1 ≤ ell) :
    hardJointGradientResponse κ η prob 1 lam R L a =
      successfulHardPrefixMap κ η prob lam R a ell
        (hardProbeJetAt (hardRadius η T) L a.2.1) := by
  rw [hardJointGradientResponse_successful hη hT hR]
  unfold successfulHardPrefixMap
  rw [successfulHiddenResponse_eq_prefix hη _ hprog]

end

end BilevelLowerBound
