/-
Copyright (c) 2026 Zhihao Gu, Qilong Wu, and Junchi Yang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zhihao Gu, Qilong Wu, Junchi Yang
-/
import BilevelLowerBoundLean.KappaEightPaperMainTheorem
import BilevelLowerBoundLean.KappaEightPaperHardInstance
import BilevelLowerBoundLean.KappaEightConditionWitness
import BilevelLowerBoundLean.KappaEightOracle
import BilevelLowerBoundLean.KappaEightHardOracleInterface
import BilevelLowerBoundLean.KappaEightSharpConstants
import BilevelLowerBoundLean.KappaEightUpperRegularity
import BilevelLowerBoundLean.KappaEightPopulationClass
import BilevelLowerBoundLean.KappaEightSimultaneousCertificates
import BilevelLowerBoundLean.KappaEightPaperFinalTheorem
import Mathlib.Util.AssertNoSorry

/-!
# Axiom and placeholder audit for the independent kappa-eight construction

This file audits the paper-facing definitions and theorems introduced in the
`KappaEight*` modules.  The final adaptive-Haar result is an explicit theorem
premise, not a Lean axiom.  Therefore `sorryAx` must not occur in any printed
dependency list, and every declaration below must pass `assert_no_sorry`.
-/

/-! ## Paper-facing type checks -/

#check BilevelLowerBound.KappaEightPopulationClassMember.lower_hessian_lipschitz
#check BilevelLowerBound.KappaEightPopulationClassMember.muG_le_muGAct
#check BilevelLowerBound.KappaEightPopulationClassMember.to_final_uniform_bounds
#check BilevelLowerBound.exists_kappaEightPaperPopulationClassMember
#check BilevelLowerBound.KappaEightBernoulliSFOMember.upper_mean
#check BilevelLowerBound.KappaEightBernoulliSFOMember.lower_mean
#check BilevelLowerBound.KappaEightBernoulliSFOMember.upper_variance
#check BilevelLowerBound.KappaEightBernoulliSFOMember.lower_variance
#check BilevelLowerBound.exists_kappaEightPaperHardBernoulliSFOMember
#check BilevelLowerBound.kappaEightAdaptiveHardLowerCallLaw_of_fresh
#check BilevelLowerBound.exists_simultaneous_kappaEight_hard_certificates
#check BilevelLowerBound.KappaEightRunFailure
#check BilevelLowerBound.ConcreteKappaEightLowerBound
#check BilevelLowerBound.KappaEightCitedAdaptiveHaarPrinciple
#check BilevelLowerBound.kappaEight_failure_for_one_algorithm
#check BilevelLowerBound.KappaEightRunFailure.intrinsic_scale_sandwich
#check BilevelLowerBound.KappaEightRunFailure.intrinsic_budget_is_covered
#check BilevelLowerBound.kappaEightPaperConstructionRegularityScale
#check BilevelLowerBound.kappaEight_final_scale_implies_regularities
#check BilevelLowerBound.concrete_kappaEight_paper_main_theorem

/-! ## Printed logical dependencies -/

#print axioms BilevelLowerBound.AmplifierAux
#print axioms BilevelLowerBound.amplifierQuadratic
#print axioms BilevelLowerBound.amplifierHessianForm
#print axioms BilevelLowerBound.attenuatedFrontier
#print axioms BilevelLowerBound.amplifiedCompensation
#print axioms BilevelLowerBound.amplifiedScalarBlock
#print axioms BilevelLowerBound.amplifierHessianForm_diagonalize
#print axioms BilevelLowerBound.amplifierHessianForm_coercive
#print axioms BilevelLowerBound.amplifierHessianForm_le
#print axioms BilevelLowerBound.amplifierHessianForm_proposed
#print axioms BilevelLowerBound.amplifiedScalarBlock_nonneg
#print axioms BilevelLowerBound.amplifiedScalarBlock_eq_zero_iff

#print axioms BilevelLowerBound.kappaEightCompensatedPair
#print axioms BilevelLowerBound.kappaEightPopulationLower
#print axioms BilevelLowerBound.kappaEightSampleLower
#print axioms BilevelLowerBound.kappaEightHardUpper
#print axioms BilevelLowerBound.kappaEightSampleLower_bernoulli_population
#print axioms BilevelLowerBound.kappaEightAuxSolution
#print axioms BilevelLowerBound.kappaEightPopulationLower_minimum
#print axioms BilevelLowerBound.kappaEightPopulationLower_unique_minimizer
#print axioms BilevelLowerBound.kappaEightHardUpper_at_proposed_solution

#print axioms BilevelLowerBound.kappaEightAttenuatedFrontier
#print axioms BilevelLowerBound.norm_iteratedFDeriv_kappaEightAttenuatedFrontier_le
#print axioms BilevelLowerBound.kappaEightAttenuatedFrontier_scales
#print axioms BilevelLowerBound.kappaEightCompensatedPair_contDiff
#print axioms BilevelLowerBound.kappaEightCompensatedPair_first_second_third_bounds
#print axioms BilevelLowerBound.exists_kappaEight_hard_compensated_pair_regularities

#print axioms BilevelLowerBound.iteratedFDeriv_amplifierQuadratic_two_apply
#print axioms BilevelLowerBound.iteratedFDeriv_amplifierQuadratic_three_eq_zero
#print axioms BilevelLowerBound.amplifierHessianForm_norm_coercive
#print axioms BilevelLowerBound.kappaEightFullBaseQuadratic
#print axioms BilevelLowerBound.kappaEightFullBaseQuadratic_contDiff
#print axioms BilevelLowerBound.norm_iteratedFDeriv_kappaEightFullBaseQuadratic_two_le_eight
#print axioms BilevelLowerBound.iteratedFDeriv_kappaEightFullBaseQuadratic_three_eq_zero
#print axioms BilevelLowerBound.kappaEightFullCompensatedPair
#print axioms BilevelLowerBound.kappaEightFullPopulationLower
#print axioms BilevelLowerBound.exists_kappaEightFullPopulationLower_regularities
#print axioms BilevelLowerBound.kappaEightLowerBaseSlice
#print axioms BilevelLowerBound.kappaEightLowerBaseSlice_coercive
#print axioms BilevelLowerBound.norm_iteratedFDeriv_kappaEightLowerBaseSlice_two_le_six
#print axioms BilevelLowerBound.kappaEightLowerBase_add_perturbation_strong_hessian
#print axioms BilevelLowerBound.kappaEightPopulationLower_second_bound
#print axioms BilevelLowerBound.kappaEightPopulationLower_third_bound
#print axioms BilevelLowerBound.kappaEightPopulationLower_strong_hessian
#print axioms BilevelLowerBound.kappaEightPopulationLower_hessian_lipschitz
#print axioms BilevelLowerBound.exists_kappaEightPopulationLower_certificates

#print axioms BilevelLowerBound.KappaEightPopulationProblem
#print axioms BilevelLowerBound.KappaEightHasUniformLowerStrongConvexity
#print axioms BilevelLowerBound.KappaEightHasBoundedUpperLowerDerivative
#print axioms BilevelLowerBound.KappaEightPopulationClassMember
#print axioms BilevelLowerBound.KappaEightIsSharpLowerHessianModulus
#print axioms BilevelLowerBound.KappaEightIsSharpLowerHessianUpperBound
#print axioms BilevelLowerBound.KappaEightLowerConditionData
#print axioms BilevelLowerBound.KappaEightLowerConditionData.kappaY
#print axioms BilevelLowerBound.KappaEightPopulationClassMember.muG_le_muGAct
#print axioms BilevelLowerBound.KappaEightBernoulliSFO
#print axioms BilevelLowerBound.KappaEightBernoulliSFOMember
#print axioms BilevelLowerBound.KappaEightAdaptiveAlgorithm

#print axioms BilevelLowerBound.kappaEightPaperLowerSolution
#print axioms BilevelLowerBound.kappaEightCandidateFirst_le_eta_of_scale
#print axioms BilevelLowerBound.kappaEightFullHardUpper
#print axioms BilevelLowerBound.kappaEightFullHardUpper_at_lowerSolution
#print axioms BilevelLowerBound.kappaEightPaperPopulationProblem
#print axioms BilevelLowerBound.exists_kappaEightPaperPopulationProblem

#print axioms BilevelLowerBound.kappaEightFullSampleLower
#print axioms BilevelLowerBound.kappaEightFullPopulationLower_eq_base_add_frontier
#print axioms BilevelLowerBound.fderiv_kappaEightFullSampleLower
#print axioms BilevelLowerBound.kappaEightFullSampleLower_bernoulli_gradient_unbiased
#print axioms BilevelLowerBound.exists_kappaEightFullCompensatedPair_gradient_bound
#print axioms BilevelLowerBound.exists_kappaEightFullSampleLower_oracle_properties

#print axioms BilevelLowerBound.kappaEightFullHardUpper_eq_sum
#print axioms BilevelLowerBound.kappaEightFullHardUpper_contDiff
#print axioms BilevelLowerBound.iteratedFDeriv_kappaEightFullLinearReadout_two_eq_zero
#print axioms BilevelLowerBound.exists_kappaEightFullHardUpper_second_regularities
#print axioms BilevelLowerBound.exists_kappaEightFullHardUpper_lowerDerivative_bound

#print axioms BilevelLowerBound.kappaEightCompensatedDerivativeFromJet
#print axioms BilevelLowerBound.fderiv_kappaEightCompensatedPair_eq_fromJet
#print axioms BilevelLowerBound.fderiv_kappaEightFullCompensatedPair_eq_fromJet
#print axioms BilevelLowerBound.kappaEightHardProbeJetAt
#print axioms BilevelLowerBound.kappaEightOracleFullHardUpper
#print axioms BilevelLowerBound.assembleKappaEightHardJointResponse
#print axioms BilevelLowerBound.kappaEightHardJointGradientResponse
#print axioms BilevelLowerBound.fderiv_kappaEightOracleFullHardUpper_as_assembled
#print axioms BilevelLowerBound.kappaEightHardJointGradientResponse_failed
#print axioms BilevelLowerBound.kappaEightHardJointGradientResponse_successful
#print axioms BilevelLowerBound.kappaEightFailedHardPrefixMap_measurable
#print axioms BilevelLowerBound.kappaEightSuccessfulHardPrefixMap_measurable
#print axioms BilevelLowerBound.assembleKappaEightHardJointResponse_continuous
#print axioms BilevelLowerBound.kappaEightHardJointGradientResponse_failed_eq_prefix
#print axioms BilevelLowerBound.kappaEightHardJointGradientResponse_successful_eq_prefix

#print axioms BilevelLowerBound.kappaEightRevealProbability
#print axioms BilevelLowerBound.kappaEightRevealProbability_pos
#print axioms BilevelLowerBound.kappaEightRevealProbability_le_one
#print axioms BilevelLowerBound.kappaEightRevealProbability_mem_unitInterval
#print axioms BilevelLowerBound.kappaEightRevealProbability_variance_le
#print axioms BilevelLowerBound.one_div_kappaEightRevealProbability
#print axioms BilevelLowerBound.kappaEightBernoulliSquaredNoise_le
#print axioms BilevelLowerBound.kappaEightFinalEta
#print axioms BilevelLowerBound.kappaEightFinalEta_pos
#print axioms BilevelLowerBound.kappaEightFinalChainLength
#print axioms BilevelLowerBound.kappaEightFinalChainLength_two_sided
#print axioms BilevelLowerBound.kappaEightComplexityScale
#print axioms BilevelLowerBound.kappaEightComplexityScale_expand
#print axioms BilevelLowerBound.kappaEightFinal_T_over_p_main_scale
#print axioms BilevelLowerBound.kappaEightCallBudget_implies_progress_condition
#print axioms BilevelLowerBound.kappaEightConditionNumber_scale_comparison
#print axioms BilevelLowerBound.kappaEightConditionNumber_callBudget_transfer
#print axioms BilevelLowerBound.kappaEightConditionNumber_scale_sandwich

#print axioms BilevelLowerBound.iteratedFDeriv_kappaEightCompensatedPair_two_eq_zero_at_fullProgress
#print axioms BilevelLowerBound.kappaEightLowerBaseSlice_weak_witness
#print axioms BilevelLowerBound.kappaEightLowerBaseSlice_strong_witness
#print axioms BilevelLowerBound.kappaEight_condition_number_comparison_of_flat_point
#print axioms BilevelLowerBound.kappaEight_hardFrontier_condition_number_comparison
#print axioms BilevelLowerBound.KappaEightLowerConditionData.condition_number_comparison_of_lower_eq
#print axioms BilevelLowerBound.exists_kappaEight_sharp_lower_hessian_modulus
#print axioms BilevelLowerBound.exists_kappaEight_sharp_lower_hessian_upper_bound
#print axioms BilevelLowerBound.exists_kappaEightFrame_sharp_lower_constants

#print axioms BilevelLowerBound.kappaEightRevealProbability_eq_revealProbability_mul
#print axioms BilevelLowerBound.mainComplexityScale_mul_eq_kappaEightComplexityScale
#print axioms BilevelLowerBound.moment_failure_of_large_event_with_margin
#print axioms BilevelLowerBound.kappaEight_main_lower_bound_assembly

#print axioms BilevelLowerBound.kappaEightRunTranscript
#print axioms BilevelLowerBound.kappaEightRunTranscript_zero
#print axioms BilevelLowerBound.kappaEightRunTranscript_succ
#print axioms BilevelLowerBound.length_kappaEightRunTranscript
#print axioms BilevelLowerBound.kappaEightRunQuery
#print axioms BilevelLowerBound.kappaEightRunOutput
#print axioms BilevelLowerBound.kappaEightRunPastMeasurableSpace
#print axioms BilevelLowerBound.kappaEightJointRunPastMeasurableSpace
#print axioms BilevelLowerBound.get_kappaEightRunTranscript_succ_last

#print axioms BilevelLowerBound.PackedKappaEightAlgorithm
#print axioms BilevelLowerBound.KappaEightCitedAdaptiveHaarRun
#print axioms BilevelLowerBound.kappaEight_expectation_from_cited_run

#print axioms BilevelLowerBound.KappaEightPopulationClassMember.mono
#print axioms BilevelLowerBound.kappaEightUniversalLowerGradientConstant
#print axioms BilevelLowerBound.kappaEightGapUpperLowerDerivativeConstant
#print axioms BilevelLowerBound.KappaEightPopulationClassMember.to_final_uniform_bounds
#print axioms BilevelLowerBound.exists_kappaEightPaperPopulationClassMember

#print axioms BilevelLowerBound.exists_kappaEightPaperHardBernoulliSFOMember
#print axioms BilevelLowerBound.kappaEightAdaptiveHardLowerCallLaw_of_fresh
#print axioms BilevelLowerBound.exists_simultaneous_kappaEight_hard_certificates

#print axioms BilevelLowerBound.KappaEightRunFailure
#print axioms BilevelLowerBound.ConcreteKappaEightLowerBound
#print axioms BilevelLowerBound.KappaEightCitedAdaptiveHaarPrinciple
#print axioms BilevelLowerBound.kappaEight_failure_for_one_algorithm
#print axioms BilevelLowerBound.KappaEightRunFailure.intrinsic_scale_sandwich
#print axioms BilevelLowerBound.KappaEightRunFailure.intrinsic_budget_is_covered
#print axioms BilevelLowerBound.kappaEightPaperConstructionRegularityScale
#print axioms BilevelLowerBound.kappaEightPaperConstructionRegularityScale_pos
#print axioms BilevelLowerBound.kappaEight_final_scale_implies_regularities
#print axioms BilevelLowerBound.concrete_kappaEight_paper_main_theorem

/-! ## Transitive no-placeholder checks -/

assert_no_sorry BilevelLowerBound.AmplifierAux
assert_no_sorry BilevelLowerBound.amplifierQuadratic
assert_no_sorry BilevelLowerBound.amplifierHessianForm
assert_no_sorry BilevelLowerBound.attenuatedFrontier
assert_no_sorry BilevelLowerBound.amplifiedCompensation
assert_no_sorry BilevelLowerBound.amplifiedScalarBlock
assert_no_sorry BilevelLowerBound.amplifierHessianForm_diagonalize
assert_no_sorry BilevelLowerBound.amplifierHessianForm_coercive
assert_no_sorry BilevelLowerBound.amplifierHessianForm_le
assert_no_sorry BilevelLowerBound.amplifierHessianForm_proposed
assert_no_sorry BilevelLowerBound.amplifiedScalarBlock_nonneg
assert_no_sorry BilevelLowerBound.amplifiedScalarBlock_eq_zero_iff

assert_no_sorry BilevelLowerBound.kappaEightCompensatedPair
assert_no_sorry BilevelLowerBound.kappaEightPopulationLower
assert_no_sorry BilevelLowerBound.kappaEightSampleLower
assert_no_sorry BilevelLowerBound.kappaEightHardUpper
assert_no_sorry BilevelLowerBound.kappaEightSampleLower_bernoulli_population
assert_no_sorry BilevelLowerBound.kappaEightAuxSolution
assert_no_sorry BilevelLowerBound.kappaEightPopulationLower_minimum
assert_no_sorry BilevelLowerBound.kappaEightPopulationLower_unique_minimizer
assert_no_sorry BilevelLowerBound.kappaEightHardUpper_at_proposed_solution

assert_no_sorry BilevelLowerBound.kappaEightAttenuatedFrontier
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_kappaEightAttenuatedFrontier_le
assert_no_sorry BilevelLowerBound.kappaEightAttenuatedFrontier_scales
assert_no_sorry BilevelLowerBound.kappaEightCompensatedPair_contDiff
assert_no_sorry BilevelLowerBound.kappaEightCompensatedPair_first_second_third_bounds
assert_no_sorry BilevelLowerBound.exists_kappaEight_hard_compensated_pair_regularities

assert_no_sorry BilevelLowerBound.iteratedFDeriv_amplifierQuadratic_two_apply
assert_no_sorry BilevelLowerBound.iteratedFDeriv_amplifierQuadratic_three_eq_zero
assert_no_sorry BilevelLowerBound.amplifierHessianForm_norm_coercive
assert_no_sorry BilevelLowerBound.kappaEightFullBaseQuadratic
assert_no_sorry BilevelLowerBound.kappaEightFullBaseQuadratic_contDiff
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_kappaEightFullBaseQuadratic_two_le_eight
assert_no_sorry BilevelLowerBound.iteratedFDeriv_kappaEightFullBaseQuadratic_three_eq_zero
assert_no_sorry BilevelLowerBound.kappaEightFullCompensatedPair
assert_no_sorry BilevelLowerBound.kappaEightFullPopulationLower
assert_no_sorry BilevelLowerBound.exists_kappaEightFullPopulationLower_regularities
assert_no_sorry BilevelLowerBound.kappaEightLowerBaseSlice
assert_no_sorry BilevelLowerBound.kappaEightLowerBaseSlice_coercive
assert_no_sorry BilevelLowerBound.norm_iteratedFDeriv_kappaEightLowerBaseSlice_two_le_six
assert_no_sorry BilevelLowerBound.kappaEightLowerBase_add_perturbation_strong_hessian
assert_no_sorry BilevelLowerBound.kappaEightPopulationLower_second_bound
assert_no_sorry BilevelLowerBound.kappaEightPopulationLower_third_bound
assert_no_sorry BilevelLowerBound.kappaEightPopulationLower_strong_hessian
assert_no_sorry BilevelLowerBound.kappaEightPopulationLower_hessian_lipschitz
assert_no_sorry BilevelLowerBound.exists_kappaEightPopulationLower_certificates

assert_no_sorry BilevelLowerBound.KappaEightPopulationProblem
assert_no_sorry BilevelLowerBound.KappaEightHasUniformLowerStrongConvexity
assert_no_sorry BilevelLowerBound.KappaEightHasBoundedUpperLowerDerivative
assert_no_sorry BilevelLowerBound.KappaEightPopulationClassMember
assert_no_sorry BilevelLowerBound.KappaEightIsSharpLowerHessianModulus
assert_no_sorry BilevelLowerBound.KappaEightIsSharpLowerHessianUpperBound
assert_no_sorry BilevelLowerBound.KappaEightLowerConditionData
assert_no_sorry BilevelLowerBound.KappaEightLowerConditionData.kappaY
assert_no_sorry BilevelLowerBound.KappaEightPopulationClassMember.muG_le_muGAct
assert_no_sorry BilevelLowerBound.KappaEightBernoulliSFO
assert_no_sorry BilevelLowerBound.KappaEightBernoulliSFOMember
assert_no_sorry BilevelLowerBound.KappaEightAdaptiveAlgorithm

assert_no_sorry BilevelLowerBound.kappaEightPaperLowerSolution
assert_no_sorry BilevelLowerBound.kappaEightCandidateFirst_le_eta_of_scale
assert_no_sorry BilevelLowerBound.kappaEightFullHardUpper
assert_no_sorry BilevelLowerBound.kappaEightFullHardUpper_at_lowerSolution
assert_no_sorry BilevelLowerBound.kappaEightPaperPopulationProblem
assert_no_sorry BilevelLowerBound.exists_kappaEightPaperPopulationProblem

assert_no_sorry BilevelLowerBound.kappaEightFullSampleLower
assert_no_sorry BilevelLowerBound.kappaEightFullPopulationLower_eq_base_add_frontier
assert_no_sorry BilevelLowerBound.fderiv_kappaEightFullSampleLower
assert_no_sorry BilevelLowerBound.kappaEightFullSampleLower_bernoulli_gradient_unbiased
assert_no_sorry BilevelLowerBound.exists_kappaEightFullCompensatedPair_gradient_bound
assert_no_sorry BilevelLowerBound.exists_kappaEightFullSampleLower_oracle_properties

assert_no_sorry BilevelLowerBound.kappaEightFullHardUpper_eq_sum
assert_no_sorry BilevelLowerBound.kappaEightFullHardUpper_contDiff
assert_no_sorry BilevelLowerBound.iteratedFDeriv_kappaEightFullLinearReadout_two_eq_zero
assert_no_sorry BilevelLowerBound.exists_kappaEightFullHardUpper_second_regularities
assert_no_sorry BilevelLowerBound.exists_kappaEightFullHardUpper_lowerDerivative_bound

assert_no_sorry BilevelLowerBound.kappaEightCompensatedDerivativeFromJet
assert_no_sorry BilevelLowerBound.fderiv_kappaEightCompensatedPair_eq_fromJet
assert_no_sorry BilevelLowerBound.fderiv_kappaEightFullCompensatedPair_eq_fromJet
assert_no_sorry BilevelLowerBound.kappaEightHardProbeJetAt
assert_no_sorry BilevelLowerBound.kappaEightOracleFullHardUpper
assert_no_sorry BilevelLowerBound.assembleKappaEightHardJointResponse
assert_no_sorry BilevelLowerBound.kappaEightHardJointGradientResponse
assert_no_sorry BilevelLowerBound.fderiv_kappaEightOracleFullHardUpper_as_assembled
assert_no_sorry BilevelLowerBound.kappaEightHardJointGradientResponse_failed
assert_no_sorry BilevelLowerBound.kappaEightHardJointGradientResponse_successful
assert_no_sorry BilevelLowerBound.kappaEightFailedHardPrefixMap_measurable
assert_no_sorry BilevelLowerBound.kappaEightSuccessfulHardPrefixMap_measurable
assert_no_sorry BilevelLowerBound.assembleKappaEightHardJointResponse_continuous
assert_no_sorry
  BilevelLowerBound.kappaEightHardJointGradientResponse_failed_eq_prefix
assert_no_sorry
  BilevelLowerBound.kappaEightHardJointGradientResponse_successful_eq_prefix

assert_no_sorry BilevelLowerBound.kappaEightRevealProbability
assert_no_sorry BilevelLowerBound.kappaEightRevealProbability_pos
assert_no_sorry BilevelLowerBound.kappaEightRevealProbability_le_one
assert_no_sorry BilevelLowerBound.kappaEightRevealProbability_mem_unitInterval
assert_no_sorry BilevelLowerBound.kappaEightRevealProbability_variance_le
assert_no_sorry BilevelLowerBound.one_div_kappaEightRevealProbability
assert_no_sorry BilevelLowerBound.kappaEightBernoulliSquaredNoise_le
assert_no_sorry BilevelLowerBound.kappaEightFinalEta
assert_no_sorry BilevelLowerBound.kappaEightFinalEta_pos
assert_no_sorry BilevelLowerBound.kappaEightFinalChainLength
assert_no_sorry BilevelLowerBound.kappaEightFinalChainLength_two_sided
assert_no_sorry BilevelLowerBound.kappaEightComplexityScale
assert_no_sorry BilevelLowerBound.kappaEightComplexityScale_expand
assert_no_sorry BilevelLowerBound.kappaEightFinal_T_over_p_main_scale
assert_no_sorry BilevelLowerBound.kappaEightCallBudget_implies_progress_condition
assert_no_sorry BilevelLowerBound.kappaEightConditionNumber_scale_comparison
assert_no_sorry BilevelLowerBound.kappaEightConditionNumber_callBudget_transfer
assert_no_sorry BilevelLowerBound.kappaEightConditionNumber_scale_sandwich

assert_no_sorry
  BilevelLowerBound.iteratedFDeriv_kappaEightCompensatedPair_two_eq_zero_at_fullProgress
assert_no_sorry BilevelLowerBound.kappaEightLowerBaseSlice_weak_witness
assert_no_sorry BilevelLowerBound.kappaEightLowerBaseSlice_strong_witness
assert_no_sorry BilevelLowerBound.kappaEight_condition_number_comparison_of_flat_point
assert_no_sorry BilevelLowerBound.kappaEight_hardFrontier_condition_number_comparison
assert_no_sorry
  BilevelLowerBound.KappaEightLowerConditionData.condition_number_comparison_of_lower_eq
assert_no_sorry BilevelLowerBound.exists_kappaEight_sharp_lower_hessian_modulus
assert_no_sorry BilevelLowerBound.exists_kappaEight_sharp_lower_hessian_upper_bound
assert_no_sorry BilevelLowerBound.exists_kappaEightFrame_sharp_lower_constants

assert_no_sorry BilevelLowerBound.kappaEightRevealProbability_eq_revealProbability_mul
assert_no_sorry BilevelLowerBound.mainComplexityScale_mul_eq_kappaEightComplexityScale
assert_no_sorry BilevelLowerBound.moment_failure_of_large_event_with_margin
assert_no_sorry BilevelLowerBound.kappaEight_main_lower_bound_assembly

assert_no_sorry BilevelLowerBound.kappaEightRunTranscript
assert_no_sorry BilevelLowerBound.kappaEightRunTranscript_zero
assert_no_sorry BilevelLowerBound.kappaEightRunTranscript_succ
assert_no_sorry BilevelLowerBound.length_kappaEightRunTranscript
assert_no_sorry BilevelLowerBound.kappaEightRunQuery
assert_no_sorry BilevelLowerBound.kappaEightRunOutput
assert_no_sorry BilevelLowerBound.kappaEightRunPastMeasurableSpace
assert_no_sorry BilevelLowerBound.kappaEightJointRunPastMeasurableSpace
assert_no_sorry BilevelLowerBound.get_kappaEightRunTranscript_succ_last

assert_no_sorry BilevelLowerBound.PackedKappaEightAlgorithm
assert_no_sorry BilevelLowerBound.KappaEightCitedAdaptiveHaarRun
assert_no_sorry BilevelLowerBound.kappaEight_expectation_from_cited_run

assert_no_sorry BilevelLowerBound.KappaEightPopulationClassMember.mono
assert_no_sorry BilevelLowerBound.kappaEightUniversalLowerGradientConstant
assert_no_sorry BilevelLowerBound.kappaEightGapUpperLowerDerivativeConstant
assert_no_sorry
  BilevelLowerBound.KappaEightPopulationClassMember.to_final_uniform_bounds
assert_no_sorry BilevelLowerBound.exists_kappaEightPaperPopulationClassMember

assert_no_sorry BilevelLowerBound.exists_kappaEightPaperHardBernoulliSFOMember
assert_no_sorry BilevelLowerBound.kappaEightAdaptiveHardLowerCallLaw_of_fresh
assert_no_sorry BilevelLowerBound.exists_simultaneous_kappaEight_hard_certificates

assert_no_sorry BilevelLowerBound.KappaEightRunFailure
assert_no_sorry BilevelLowerBound.ConcreteKappaEightLowerBound
assert_no_sorry BilevelLowerBound.KappaEightCitedAdaptiveHaarPrinciple
assert_no_sorry BilevelLowerBound.kappaEight_failure_for_one_algorithm
assert_no_sorry BilevelLowerBound.KappaEightRunFailure.intrinsic_scale_sandwich
assert_no_sorry BilevelLowerBound.KappaEightRunFailure.intrinsic_budget_is_covered
assert_no_sorry BilevelLowerBound.kappaEightPaperConstructionRegularityScale
assert_no_sorry BilevelLowerBound.kappaEightPaperConstructionRegularityScale_pos
assert_no_sorry BilevelLowerBound.kappaEight_final_scale_implies_regularities
assert_no_sorry BilevelLowerBound.concrete_kappaEight_paper_main_theorem
