/-
Copyright (c) 2026 Zhihao Gu, Qilong Wu, and Junchi Yang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zhihao Gu, Qilong Wu, Junchi Yang
-/
import BilevelLowerBoundLean.KappaEightPaperMainTheorem
import BilevelLowerBoundLean.KappaEightSimultaneousCertificates

/-!
# Concrete outer quantifiers for the `kappa_y^8 epsilon^-6` lower bound

The final statement has the literal order `exists d, forall algorithm,
exists problem, exists oracle`.  The random output is generated by the exact
recursive amplified interaction.  The only external premise is the named
adaptive-Haar principle.  It packages deterministic-prefix Haar
disintegration, its independent bits-only stopped-prefix specialization, and
the spherical-cap estimate; these measure-theoretic facts are not rebuilt
from Stiefel Haar measure in Lean.  Its returned structure exposes the seed
law, fresh samples, conditional caps, residual geometry, and actual run output.
-/

open MeasureTheory ProbabilityTheory Set
open scoped MeasureTheory ProbabilityTheory

namespace BilevelLowerBound

noncomputable section

/-- Failure certificate for one fixed amplified population problem and SFO.
The `3/2` and `9/4` margins retain the strict separation obtained from the
fixed-frame event of probability at least `3/4` on which the gradient norm is
strictly larger than `2 * epsilon`. -/
structure KappaEightRunFailure
    {N d : ℕ} {Seed : Type} {mSeed : MeasurableSpace Seed}
    (A : @KappaEightAdaptiveAlgorithm N (KappaEightEuclidean d) Seed
      inferInstance inferInstance inferInstance mSeed)
    (P : KappaEightPopulationProblem (KappaEightEuclidean d))
    (O : KappaEightBernoulliSFO P)
    (epsilon kappa Ckappa : ℝ) where
  conditionData : KappaEightLowerConditionData P
  conditionLower : kappa ≤ conditionData.kappaY
  conditionUpper : conditionData.kappaY ≤ Ckappa * kappa
  Omega : Type
  omegaMeasurable : MeasurableSpace Omega
  omegaMeasure : @Measure Omega omegaMeasurable
  omegaProbability : IsProbabilityMeasure omegaMeasure
  seed : Omega → Seed
  seed_measurable : @Measurable Omega Seed omegaMeasurable mSeed seed
  seed_law : Measure.map seed omegaMeasure = A.seedMeasure
  bits : Omega → Fin N → Bool
  fresh : ∀ t,
    @FreshBernoulliEvent Omega omegaMeasurable omegaMeasure
      (kappaEightRunPastMeasurableSpace A O seed bits t)
      (kappaEightRunSuccessEvent bits t) O.probability
  firstMomentFailure :
    3 * epsilon / 2 < ∫ omega,
      ‖gradient P.hyperObjective
        (kappaEightRunOutput A O (seed omega) (bits omega))‖ ∂omegaMeasure
  secondMomentFailure :
    9 * epsilon ^ 2 / 4 < ∫ omega,
      ‖gradient P.hyperObjective
        (kappaEightRunOutput A O (seed omega) (bits omega))‖ ^ 2 ∂omegaMeasure

/-- Concrete minimax quantifier order for the amplified family. -/
def ConcreteKappaEightLowerBound
    (N T : ℕ) (CH : ℝ)
    (Delta epsilon kappa sigma Lf Lg rho Cf muG Ckappa : ℝ) : Prop :=
  ∃ d : ℕ, requiredHaarDimension CH (N + 1) T ≤ d ∧
    ∀ A : PackedKappaEightAlgorithm N d,
      ∃ P : KappaEightPopulationProblem (KappaEightEuclidean d),
        KappaEightPopulationClassMember P Lf Lg rho Cf muG Delta ∧
        ∃ O : KappaEightBernoulliSFO P,
          KappaEightBernoulliSFOMember O sigma ∧
          Nonempty
            (@KappaEightRunFailure N d A.Seed A.seedMeasurable A.algorithm
              P O epsilon kappa Ckappa)

/-- Sole external random-rotation principle for the concrete amplified hard
family.  Unlike an unrestricted oracle principle, its population problems
and SFOs are definitionally the two-coordinate constructions proved in this
repository to satisfy the failed/successful prefix interface.  Its hypotheses
also impose the nondegenerate oracle regime `0 < Cvar` and `0 ≤ sigma` used by
the Bernoulli reveal law.  The external geometric content includes the
independent stopped-prefix passage used when the revealed prefix is determined
only by those Bernoulli bits.  It does not assume the lower-bound conclusion:
it supplies the explicit probabilistic run interface from which the checked
assembly derives that conclusion. -/
def KappaEightCitedAdaptiveHaarPrinciple (CH : ℝ) : Prop :=
  ∀ {N d T : ℕ} {Seed : Type} {mSeed : MeasurableSpace Seed}
    (A : @KappaEightAdaptiveAlgorithm N (KappaEightEuclidean d) Seed
      inferInstance inferInstance inferInstance mSeed)
    {Cvar eta kappa sigma : ℝ},
    (hCvar : 0 < Cvar) → (hsigma : 0 ≤ sigma) →
    (heta : 0 < eta) → (hetaOne : eta ≤ 1) →
    (hkappa : 1 < kappa) → (hT : 0 < T) →
    (hsmall : ∀ (U : ChainVector T →ₗᵢ[ℝ] KappaEightEuclidean d)
      (x : KappaEightEuclidean d),
      |amplifierDiag kappa * attenuatedFrontier kappa
        (hardFrontierMap eta (hiddenFrameTranspose U) (kappa • x))| ≤ eta) →
    requiredHaarDimension CH (N + 1) T ≤ d →
    ∃ q : ℝ,
      Nonempty (KappaEightCitedAdaptiveHaarRun A
        (fun U ↦ kappaEightPaperPopulationProblem eta kappa U
          heta hkappa (hsmall U))
        (fun U ↦ kappaEightPaperHardBernoulliSFO Cvar eta kappa sigma U
          heta hkappa (hsmall U))
        Cvar eta kappa sigma q)

/-- Fixed-frame failure extracted from one cited amplified Haar run. -/
theorem kappaEight_failure_for_one_algorithm
    {N d T : ℕ} {Seed : Type} {mSeed : MeasurableSpace Seed}
    (A : @KappaEightAdaptiveAlgorithm N (KappaEightEuclidean d) Seed
      inferInstance inferInstance inferInstance mSeed)
    (P : (ChainVector T →ₗᵢ[ℝ] KappaEightEuclidean d) →
      KappaEightPopulationProblem (KappaEightEuclidean d))
    (O : ∀ U, KappaEightBernoulliSFO (P U))
    {Delta epsilon kappa sigma CDelta Cvar creg q
      Lf Lg rho Cf muG : ℝ}
    (hDelta : 0 < Delta) (hepsilon : 0 < epsilon) (hkappa : 2 ≤ kappa)
    (hsigma : 0 ≤ sigma) (hCDelta : 0 < CDelta)
    (hchainGap : chainGapConstant ≤ CDelta) (hcreg : 0 < creg)
    (hCvar : 0 < Cvar)
    (haccuracy : epsilon ≤ finalAccuracyConstant CDelta creg *
      min 1 (Real.sqrt Delta))
    (hTdef : T = kappaEightFinalChainLength Delta CDelta epsilon kappa)
    (hN : (N : ℝ) ≤ kappaEightLowerBoundConstant CDelta Cvar *
      kappaEightComplexityScale Delta epsilon kappa sigma)
    (hhyper : ∀ U, (P U).hyperObjective =
      hardHyperObjective (kappaEightFinalEta epsilon kappa) kappa U)
    (hprob : ∀ U, (O U).probability =
      kappaEightRevealProbability Cvar
        (kappaEightFinalEta epsilon kappa) kappa sigma)
    (hframe : ∀ U,
      KappaEightPopulationClassMember (P U) Lf Lg rho Cf muG Delta ∧
      KappaEightBernoulliSFOMember (O U) sigma ∧
      ∃ data : KappaEightLowerConditionData (P U),
        kappa ≤ data.kappaY ∧ data.kappaY ≤ 14 * kappa)
    (H : KappaEightCitedAdaptiveHaarRun A P O Cvar
      (kappaEightFinalEta epsilon kappa) kappa sigma q) :
    ∃ P0 : KappaEightPopulationProblem (KappaEightEuclidean d),
      KappaEightPopulationClassMember P0 Lf Lg rho Cf muG Delta ∧
      ∃ O0 : KappaEightBernoulliSFO P0,
        KappaEightBernoulliSFOMember O0 sigma ∧
        Nonempty (@KappaEightRunFailure N d Seed mSeed A P0 O0
          epsilon kappa 14) := by
  obtain ⟨U0, _hgap, hmean, hmeanSq⟩ :=
    kappaEight_expectation_from_cited_run A P O hCDelta hchainGap hcreg
      hDelta hkappa hepsilon hsigma hCvar haccuracy hTdef hN H
  obtain ⟨hpop, hO, data, hcondLower, hcondUpper⟩ := hframe U0
  refine ⟨P U0, hpop, O U0, hO, ⟨?_⟩⟩
  refine
    { conditionData := data
      conditionLower := hcondLower
      conditionUpper := by simpa using hcondUpper
      Omega := H.Omega
      omegaMeasurable := H.omegaMeasurable
      omegaMeasure := H.omegaMeasure
      omegaProbability := H.omegaProbability
      seed := H.seed
      seed_measurable := H.seed_measurable
      seed_law := H.seed_law
      bits := H.bits
      fresh := ?_
      firstMomentFailure := ?_
      secondMomentFailure := ?_ }
  · intro t
    rw [hprob U0]
    exact H.sectionFresh U0 t
  · rw [hhyper U0]
    simpa only [H.output_eq_run U0] using hmean
  · rw [hhyper U0]
    simpa only [H.output_eq_run U0] using hmeanSq

/-! ## Intrinsic-condition-number replacement -/

theorem KappaEightRunFailure.intrinsic_scale_sandwich
    {N d : ℕ} {Seed : Type} {mSeed : MeasurableSpace Seed}
    {A : @KappaEightAdaptiveAlgorithm N (KappaEightEuclidean d) Seed
      inferInstance inferInstance inferInstance mSeed}
    {P : KappaEightPopulationProblem (KappaEightEuclidean d)}
    {O : KappaEightBernoulliSFO P}
    {Delta epsilon kappa sigma : ℝ}
    (H : KappaEightRunFailure A P O epsilon kappa 14)
    (hDelta : 0 ≤ Delta) (hepsilon : 0 < epsilon)
    (hkappa : 0 ≤ kappa) (hsigma : 0 ≤ sigma) :
    kappaEightComplexityScale Delta epsilon kappa sigma ≤
        kappaEightComplexityScale Delta epsilon
          H.conditionData.kappaY sigma ∧
      kappaEightComplexityScale Delta epsilon
          H.conditionData.kappaY sigma / 14 ^ 8 ≤
        kappaEightComplexityScale Delta epsilon kappa sigma := by
  have hkappaY : 0 ≤ H.conditionData.kappaY :=
    hkappa.trans H.conditionLower
  exact kappaEightConditionNumber_scale_sandwich hDelta hepsilon hkappa
    hkappaY hsigma (by norm_num) H.conditionLower H.conditionUpper

theorem KappaEightRunFailure.intrinsic_budget_is_covered
    {N d : ℕ} {Seed : Type} {mSeed : MeasurableSpace Seed}
    {A : @KappaEightAdaptiveAlgorithm N (KappaEightEuclidean d) Seed
      inferInstance inferInstance inferInstance mSeed}
    {P : KappaEightPopulationProblem (KappaEightEuclidean d)}
    {O : KappaEightBernoulliSFO P}
    {Delta epsilon kappa sigma cLB : ℝ}
    (H : KappaEightRunFailure A P O epsilon kappa 14)
    (hDelta : 0 ≤ Delta) (hepsilon : 0 < epsilon)
    (hkappa : 0 ≤ kappa) (hsigma : 0 ≤ sigma) (hcLB : 0 ≤ cLB)
    (hN : (N : ℝ) ≤ (cLB / 14 ^ 8) *
      kappaEightComplexityScale Delta epsilon
        H.conditionData.kappaY sigma) :
    (N : ℝ) ≤ cLB *
      kappaEightComplexityScale Delta epsilon kappa sigma := by
  exact kappaEightConditionNumber_callBudget_transfer hDelta hepsilon
    hkappa (hkappa.trans H.conditionLower) hsigma (by norm_num) hcLB
    H.conditionUpper hN

/-! ## A regularity scale for the final parameter choice -/

def kappaEightPaperConstructionRegularityScale
    (Ctheta CHess : ℝ) : ℝ :=
  min (1 / (1 + 3 * Ctheta)) (1 / (1 + 2 * CHess))

theorem kappaEightPaperConstructionRegularityScale_pos
    {Ctheta CHess : ℝ} (hCtheta : 0 ≤ Ctheta) (hCHess : 0 ≤ CHess) :
    0 < kappaEightPaperConstructionRegularityScale Ctheta CHess := by
  unfold kappaEightPaperConstructionRegularityScale
  exact lt_min (by positivity) (by positivity)

theorem kappaEight_final_scale_implies_regularities
    {Ctheta CHess eta kappa : ℝ}
    (hCtheta : 0 ≤ Ctheta) (hCHess : 0 ≤ CHess)
    (hkappa : 1 ≤ kappa)
    (hscale : eta ≤
      kappaEightPaperConstructionRegularityScale Ctheta CHess / kappa) :
    eta ≤ 1 ∧ 3 * Ctheta * eta ≤ 1 ∧ CHess * eta ≤ 1 / 2 := by
  have hkpos : 0 < kappa := lt_of_lt_of_le (by norm_num) hkappa
  have hregPos := kappaEightPaperConstructionRegularityScale_pos
    hCtheta hCHess
  have hetaReg : eta ≤
      kappaEightPaperConstructionRegularityScale Ctheta CHess :=
    hscale.trans (div_le_self hregPos.le hkappa)
  have hleft : kappaEightPaperConstructionRegularityScale Ctheta CHess ≤
      1 / (1 + 3 * Ctheta) := min_le_left _ _
  have hright : kappaEightPaperConstructionRegularityScale Ctheta CHess ≤
      1 / (1 + 2 * CHess) := min_le_right _ _
  have hetaLeft := hetaReg.trans hleft
  have hetaRight := hetaReg.trans hright
  have hdenLeft : 0 < 1 + 3 * Ctheta := by positivity
  have hdenRight : 0 < 1 + 2 * CHess := by positivity
  have hleftOne : 1 / (1 + 3 * Ctheta) ≤ 1 :=
    (div_le_one hdenLeft).2 (by linarith)
  constructor
  · exact hetaLeft.trans hleftOne
  constructor
  · have hthreeTheta : 0 ≤ 3 * Ctheta := by positivity
    have hmul := mul_le_mul_of_nonneg_left hetaLeft hthreeTheta
    calc
      3 * Ctheta * eta ≤ 3 * Ctheta * (1 / (1 + 3 * Ctheta)) := hmul
      _ = (3 * Ctheta) / (1 + 3 * Ctheta) := by ring
      _ ≤ 1 := (div_le_one hdenLeft).2 (by linarith)
  · have hmul := mul_le_mul_of_nonneg_left hetaRight hCHess
    calc
      CHess * eta ≤ CHess * (1 / (1 + 2 * CHess)) := hmul
      _ = CHess / (1 + 2 * CHess) := by ring
      _ ≤ 1 / 2 := by
        apply (div_le_iff₀ hdenRight).2
        nlinarith

/-! ## Fully quantified theorem -/

theorem concrete_kappaEight_paper_main_theorem
    (CH : ℝ) (hHaar : KappaEightCitedAdaptiveHaarPrinciple CH) :
    ∃ cLB cEpsilon Lf Lg rho : ℝ,
      0 < cLB ∧ 0 < cEpsilon ∧ 0 < Lf ∧ 0 < Lg ∧ 0 < rho ∧
      ∀ Delta : ℝ, 0 < Delta →
        ∃ Cf : ℝ, 0 < Cf ∧
          ∀ (kappa sigma epsilon : ℝ) (N : ℕ),
            2 ≤ kappa → 0 ≤ sigma → 0 < epsilon →
            epsilon ≤ cEpsilon * min 1 (Real.sqrt Delta) →
            (N : ℝ) ≤ cLB *
              kappaEightComplexityScale Delta epsilon kappa sigma →
            ConcreteKappaEightLowerBound N
              (kappaEightFinalChainLength Delta populationChainGapConstant
                epsilon kappa)
              CH Delta epsilon kappa sigma Lf Lg rho Cf
              (1 / (2 * kappa)) 14 := by
  obtain ⟨Ctheta, CHess, Cthird, Ca, Cvar, hCtheta, hCHess,
      hCthird, hCa, hCvar, hcert⟩ :=
    exists_simultaneous_kappaEight_hard_certificates
  let CDelta := populationChainGapConstant
  let creg := kappaEightPaperConstructionRegularityScale Ctheta CHess
  let cLB := kappaEightLowerBoundConstant CDelta Cvar
  let cEpsilon := finalAccuracyConstant CDelta creg
  let Lf := Ca + 1 / 4
  let Lg := kappaEightUniversalLowerGradientConstant CHess
  let rho := Cthird + 1
  have hCDelta : 0 < CDelta := by
    simpa [CDelta, populationChainGapConstant, chainGapConstant] using
      chainGapConstant_pos
  have hcreg : 0 < creg :=
    kappaEightPaperConstructionRegularityScale_pos hCtheta hCHess
  have hcLB : 0 < cLB := by
    unfold cLB kappaEightLowerBoundConstant
    positivity
  have hcEpsilon : 0 < cEpsilon :=
    finalAccuracyConstant_pos hCDelta hcreg
  have hLf : 0 < Lf := by dsimp [Lf]; positivity
  have hLg : 0 < Lg := by
    dsimp [Lg, kappaEightUniversalLowerGradientConstant]
    linarith
  have hrho : 0 < rho := by dsimp [rho]; linarith
  refine ⟨cLB, cEpsilon, Lf, Lg, rho, hcLB, hcEpsilon,
    hLf, hLg, hrho, ?_⟩
  intro Delta hDelta
  let Cf := kappaEightGapUpperLowerDerivativeConstant Ca CDelta Delta
  have hCf : 0 < Cf := by
    dsimp [Cf, kappaEightGapUpperLowerDerivativeConstant]
    have hsqrt : 0 ≤ Real.sqrt (Delta / CDelta) := Real.sqrt_nonneg _
    have hcoef : 0 ≤ Ca + 230 / 4 := by positivity
    nlinarith [mul_nonneg hcoef hsqrt]
  refine ⟨Cf, hCf, ?_⟩
  intro kappa sigma epsilon N hkappa hsigma hepsilon haccuracy hN
  let eta := kappaEightFinalEta epsilon kappa
  let T := kappaEightFinalChainLength Delta CDelta epsilon kappa
  have hparams := final_parameters_basic hCDelta hcreg hDelta hkappa
    hepsilon haccuracy
  have hreg := kappaEight_final_scale_implies_regularities hCtheta hCHess
    (show 1 ≤ kappa by linarith) hparams.2.1
  have hT : 0 < T := by
    change 0 < finalChainLength Delta CDelta epsilon kappa
    exact hparams.2.2.1
  have hgapHalf : CDelta * eta ^ 2 * T ≤ Delta / 2 := by
    exact final_initial_gap_le_half hCDelta hparams.1 hparams.2.2.2.2
  have hgap : populationChainGapConstant * eta ^ 2 * T ≤ Delta := by
    change CDelta * eta ^ 2 * T ≤ Delta
    exact hgapHalf.trans (by linarith)
  obtain ⟨d, hdimension⟩ := exists_dimension_choice CH (N + 1) T
  unfold ConcreteKappaEightLowerBound
  refine ⟨d, hdimension, ?_⟩
  intro packedA
  let A := packedA.algorithm
  have hsmall : ∀ U : ChainVector T →ₗᵢ[ℝ] KappaEightEuclidean d,
      ∀ x : KappaEightEuclidean d,
        |amplifierDiag kappa * attenuatedFrontier kappa
          (hardFrontierMap eta (hiddenFrameTranspose U) (kappa • x))| ≤
          eta := by
    intro U
    exact (hcert hparams.1 hreg.1 hkappa hT hsigma hreg.2.1
      hreg.2.2 hgap U).choose
  let P : (ChainVector T →ₗᵢ[ℝ] KappaEightEuclidean d) →
      KappaEightPopulationProblem (KappaEightEuclidean d) :=
    fun U ↦ kappaEightPaperPopulationProblem eta kappa U hparams.1
      (by linarith) (hsmall U)
  let O : ∀ U, KappaEightBernoulliSFO (P U) :=
    fun U ↦ kappaEightPaperHardBernoulliSFO Cvar eta kappa sigma U
      hparams.1 (by linarith) (hsmall U)
  have hframe : ∀ U,
      KappaEightPopulationClassMember (P U) Lf Lg rho Cf
          (1 / (2 * kappa)) Delta ∧
        KappaEightBernoulliSFOMember (O U) sigma ∧
        ∃ data : KappaEightLowerConditionData (P U),
          kappa ≤ data.kappaY ∧ data.kappaY ≤ 14 * kappa := by
    intro U
    obtain ⟨hsmallU, hpopRaw, hOU, data, hcondLower, hcondUpper⟩ :=
      hcert hparams.1 hreg.1 hkappa hT hsigma hreg.2.1
        hreg.2.2 hgap U
    have hsmallEq : hsmallU = hsmall U := Subsingleton.elim _ _
    subst hsmallEq
    have hpopUniform :=
      KappaEightPopulationClassMember.to_final_uniform_bounds
        hCDelta hparams.1.le hDelta.le hCa
        (show CDelta * eta ^ 2 * T ≤ Delta from hgap) hpopRaw
    have hpop : KappaEightPopulationClassMember (P U) Lf Lg rho Cf
        (1 / (2 * kappa)) Delta := by
      apply hpopUniform.mono le_rfl le_rfl _ le_rfl le_rfl le_rfl
      dsimp [rho]
      linarith
    have hOU' : KappaEightBernoulliSFOMember (O U) sigma := by
      change KappaEightBernoulliSFOMember (O U) sigma at hOU
      exact hOU
    exact ⟨by simpa [P, eta, kappaEightFinalEta,
        kappaEightEuclideanNormedSpace] using hpop,
      hOU',
      by simpa [P, eta, kappaEightFinalEta,
        kappaEightEuclideanNormedSpace] using
          ⟨data, hcondLower, hcondUpper⟩⟩
  have hhyper : ∀ U, (P U).hyperObjective =
      hardHyperObjective eta kappa U := by
    intro U
    rfl
  have hprob : ∀ U, (O U).probability =
      kappaEightRevealProbability Cvar eta kappa sigma := by
    intro U
    rfl
  unfold KappaEightCitedAdaptiveHaarPrinciple at hHaar
  obtain ⟨q, ⟨Hraw⟩⟩ := hHaar A (Cvar := Cvar) (eta := eta)
    (kappa := kappa) (sigma := sigma) hCvar hsigma hparams.1 hreg.1
    (lt_of_lt_of_le (by norm_num) hkappa) hT hsmall hdimension
  have H : KappaEightCitedAdaptiveHaarRun A P O Cvar eta kappa sigma q := by
    simpa [P, O] using Hraw
  obtain ⟨P0, hpop0, O0, hO0, hfailure⟩ :=
    kappaEight_failure_for_one_algorithm A P O hDelta hepsilon hkappa
      hsigma hCDelta
      (by simpa [CDelta, populationChainGapConstant, chainGapConstant])
      hcreg hCvar haccuracy (by rfl) hN
      (by simpa [eta] using hhyper) (by simpa [eta] using hprob)
      hframe H
  exact ⟨P0, hpop0, O0, hO0, hfailure⟩

end

end BilevelLowerBound
