/-
Copyright (c) 2026 Zhihao Gu, Qilong Wu, and Junchi Yang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zhihao Gu, Qilong Wu, Junchi Yang
-/
import BilevelLowerBoundLean.SharpConstants

/-!
# Exact recursive interaction of a paper algorithm and Bernoulli SFO

This is the direct Lean counterpart of equations defining the original
query--response transcript.  It prevents the final theorem from using an
arbitrary random output unrelated to the algorithm and oracle.
-/

namespace BilevelLowerBound

noncomputable section

/-- Transcript after `t` recursive calls.  The definition is total for all
natural `t`; after the budget `N` it leaves the terminal transcript fixed. -/
def paperRunTranscript
    {E Seed : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [MeasurableSpace E] [MeasurableSpace Seed]
    {N : ℕ} {P : PaperPopulationProblem E}
    (A : PaperAdaptiveAlgorithm N E Seed) (O : PaperBernoulliSFO P)
    (seed : Seed) (bits : Fin N → Bool) : ℕ → PaperOriginalTranscript E
  | 0 => []
  | t + 1 =>
      if ht : t < N then
        let i : Fin N := ⟨t, ht⟩
        let previous := paperRunTranscript A O seed bits t
        let query := A.query i seed previous
        previous ++ [(query, O.response (bits i) query)]
      else
        paperRunTranscript A O seed bits t

@[simp]
theorem paperRunTranscript_zero
    {E Seed : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [MeasurableSpace E] [MeasurableSpace Seed]
    {N : ℕ} {P : PaperPopulationProblem E}
    (A : PaperAdaptiveAlgorithm N E Seed) (O : PaperBernoulliSFO P)
    (seed : Seed) (bits : Fin N → Bool) :
    paperRunTranscript A O seed bits 0 = [] := rfl

theorem paperRunTranscript_succ
    {E Seed : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [MeasurableSpace E] [MeasurableSpace Seed]
    {N : ℕ} {P : PaperPopulationProblem E}
    (A : PaperAdaptiveAlgorithm N E Seed) (O : PaperBernoulliSFO P)
    (seed : Seed) (bits : Fin N → Bool) {t : ℕ} (ht : t < N) :
    paperRunTranscript A O seed bits (t + 1) =
      let i : Fin N := ⟨t, ht⟩
      let previous := paperRunTranscript A O seed bits t
      let query := A.query i seed previous
      previous ++ [(query, O.response (bits i) query)] := by
  rw [paperRunTranscript]
  simp only [dif_pos ht]

/-- Before the budget is exhausted, the recursive transcript has exactly one
query--response pair per call. -/
theorem length_paperRunTranscript
    {E Seed : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [MeasurableSpace E] [MeasurableSpace Seed]
    {N : ℕ} {P : PaperPopulationProblem E}
    (A : PaperAdaptiveAlgorithm N E Seed) (O : PaperBernoulliSFO P)
    (seed : Seed) (bits : Fin N → Bool) :
    ∀ t ≤ N, (paperRunTranscript A O seed bits t).length = t := by
  intro t htN
  induction t with
  | zero => simp
  | succ t iht =>
      have ht : t < N := by omega
      rw [paperRunTranscript_succ A O seed bits ht]
      simp [iht (by omega)]

/-- The actual query issued at call `t`, as a function of the seed and all
fresh Bernoulli bits. -/
def paperRunQuery
    {E Seed : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [MeasurableSpace E] [MeasurableSpace Seed]
    {N : ℕ} {P : PaperPopulationProblem E}
    (A : PaperAdaptiveAlgorithm N E Seed) (O : PaperBernoulliSFO P)
    (seed : Seed) (bits : Fin N → Bool) (t : Fin N) :
    PaperQueryPoint E :=
  A.query t seed (paperRunTranscript A O seed bits t.val)

/-- Final algorithm output after the exact `N`-call interaction. -/
def paperRunOutput
    {E Seed : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [MeasurableSpace E] [MeasurableSpace Seed]
    {N : ℕ} {P : PaperPopulationProblem E}
    (A : PaperAdaptiveAlgorithm N E Seed) (O : PaperBernoulliSFO P)
    (seed : Seed) (bits : Fin N → Bool) : E :=
  A.output seed (paperRunTranscript A O seed bits N)

/-- The sigma-field available immediately before call `t` in the exact
paper interaction.  It is generated by the master seed and the original
query--response transcript after the first `t` calls.  In particular, it
does not gift the latent Bernoulli bits or hidden frame to the algorithm. -/
@[instance_reducible]
def paperRunPastMeasurableSpace
    {E Seed Omega : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [MeasurableSpace E] {mSeed : MeasurableSpace Seed}
    {N : ℕ} {P : PaperPopulationProblem E}
    (A : @PaperAdaptiveAlgorithm N E Seed _ _ _ mSeed)
    (O : PaperBernoulliSFO P)
    (seed : Omega → Seed) (bits : Omega → Fin N → Bool)
    (t : Fin N) : MeasurableSpace Omega :=
  MeasurableSpace.comap
    (fun omega ↦
      (seed omega,
        paperRunTranscript A O (seed omega) (bits omega) t.val))
    (explicitProductMeasurableSpace mSeed A.transcriptMeasurableSpace)

/-- The fresh-success event at call `t` for the exact recursive run. -/
def paperRunSuccessEvent
    {Omega : Type*} {N : ℕ}
    (bits : Omega → Fin N → Bool) (t : Fin N) : Set Omega :=
  {omega | bits omega t = true}

/-- The augmented pre-query sigma-field used in the random-frame proof.  It
contains the proof-distribution frame in addition to the seed and the
original transcript, but it is still generated by the *actual* recursive
interaction.  Fresh Bernoulli bits are independent of this stronger past. -/
@[instance_reducible]
def paperJointRunPastMeasurableSpace
    {E Seed Omega Frame : Type*}
    [NormedAddCommGroup E] [NormedSpace ℝ E] [MeasurableSpace E]
    {mSeed : MeasurableSpace Seed}
    (mFrame : MeasurableSpace Frame)
    {N : ℕ} (P : Frame → PaperPopulationProblem E)
    (A : @PaperAdaptiveAlgorithm N E Seed _ _ _ mSeed)
    (O : ∀ U, PaperBernoulliSFO (P U))
    (seed : Omega → Seed) (bits : Omega → Fin N → Bool)
    (t : Fin N) : MeasurableSpace (Frame × Omega) :=
  MeasurableSpace.comap
    (fun z ↦
      (z.1,
        (seed z.2,
          paperRunTranscript A (O z.1) (seed z.2) (bits z.2) t.val)))
    (explicitProductMeasurableSpace mFrame
      (explicitProductMeasurableSpace mSeed
        A.transcriptMeasurableSpace))

/-- The transcript entry appended at call `t` contains precisely the query
selected from the preceding transcript and the oracle response to that query. -/
theorem get_paperRunTranscript_succ_last
    {E Seed : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [MeasurableSpace E] [MeasurableSpace Seed]
    {N : ℕ} {P : PaperPopulationProblem E}
    (A : PaperAdaptiveAlgorithm N E Seed) (O : PaperBernoulliSFO P)
    (seed : Seed) (bits : Fin N → Bool) (t : Fin N) :
    (paperRunTranscript A O seed bits (t.val + 1)).getLast? =
      some (paperRunQuery A O seed bits t,
        O.response (bits t) (paperRunQuery A O seed bits t)) := by
  rw [paperRunTranscript_succ A O seed bits t.isLt]
  simp [paperRunQuery]

end

end BilevelLowerBound
